import Zeta2Lean.Pair.Proofs.Landscape.Numerics

/-!
# (L-ii) The real profile of configuration E: `Φ(ξ, 0) ≤ -18/25` on `[1/40, 7/100]`

`Preal ξ = ∑_j s_j (ξ + A_j) log|ξ + A_j|` is `PhiE ξ 0` (`Growth.lean`, `PhiE_zero_eq_Preal`;
the linear terms cancel because `∑ η_p = 0`).

**Certificate** (generated by `Landscape/gen/lean_real.py`, exact rational arithmetic):
`[1/40, 7/100]` is cut into nine cells with endpoints in `(1/2000) ℤ` (a breakpoint at `1/20`,
where `ξ - 1/20` changes sign).  On each cell every summand `s_j x log x` (at `x = ξ + A_j`) is
monotone (`xlx_mono`, `xlx_anti_pos`, `xlx_anti_neg`: all fourteen arguments stay in `[2/5, ∞)`,
`[0, 1/3]` or `[-1/3, 0]`), so it is bounded by its value at the appropriate endpoint; these values
are bounded by the rational certificates for `log` of `Numerics.lean`, and the sum of the fourteen
bounds is `≤ -18/25` (true maximum of `Φ(·, 0)`: `-0.80049` at `ξ ≈ 0.02503`).
-/

set_option linter.style.longLine false

open Real

noncomputable section

namespace Zeta2.Pair.Landscape

/-- The real profile `Φ(ξ, 0)` of configuration E (`η = (-17, 1, 2, 3, 5, 6)/40`). -/
def Preal (ξ : ℝ) : ℝ :=
  (xlx (ξ + 23 / 40) - xlx (ξ + 17 / 40)) + (xlx (ξ + 41 / 40) - xlx (ξ - 1 / 40)) +
    (xlx (ξ + 21 / 20) - xlx (ξ - 1 / 20)) + (xlx (ξ + 43 / 40) - xlx (ξ - 3 / 40)) +
    (xlx (ξ + 9 / 8) - xlx (ξ - 1 / 8)) + (xlx (ξ + 23 / 20) - xlx (ξ - 3 / 20)) -
    6 * (xlx (ξ + 1) - xlx ξ)

/-! ## Certified values of `x log x` at the grid points -/

theorem rx1 : xlx (151 / 250 : ℝ) ≤ (-(76131343198837 / 250000000000000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (151 / 250 : ℝ)) (z := (13 / 138 : ℝ)) (U := (-504181080787 / 1000000000000 : ℝ)) 1 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx2 : (-(3593284698141 / 10000000000000) : ℝ) ≤ xlx (9 / 20 : ℝ) := by
  have h := (le_log_of_le_mul (q := (9 / 20 : ℝ)) (z := (2 / 7 : ℝ)) (L := (-399253855349 / 500000000000 : ℝ)) 2 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  unfold xlx; linarith

theorem rx3 : xlx (527 / 500 : ℝ) ≤ (692905530331 / 12500000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (527 / 500 : ℝ)) (z := (27 / 1027 : ℝ)) (U := (1314811253 / 25000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx4 : (-(5521460919783 / 250000000000000) : ℝ) ≤ xlx (1 / 250 : ℝ) := by
  have h := (le_log_of_le_mul (q := (1 / 250 : ℝ)) (z := (3 / 253 : ℝ)) (L := (-5521460919783 / 1000000000000 : ℝ)) 8 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  unfold xlx; linarith

theorem rx5 : xlx (1079 / 1000 : ℝ) ≤ (20510356622951 / 250000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (1079 / 1000 : ℝ)) (z := (79 / 2079 : ℝ)) (U := (19008671569 / 250000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx6 : (81127889633679 / 1000000000000000 : ℝ) ≤ xlx (-(21 / 1000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (21 / 1000 : ℝ)) (z := (43 / 293 : ℝ)) (U := (-3863232839699 / 1000000000000 : ℝ)) 6 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  rw [xlx_neg]; unfold xlx; linarith

theorem rx7 : xlx (138 / 125 : ℝ) ≤ (1365371280399 / 12500000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (138 / 125 : ℝ)) (z := (13 / 263 : ℝ)) (U := (19787989571 / 200000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx8 : (8852452408427 / 62500000000000 : ℝ) ≤ xlx (-(23 / 500) : ℝ) := by
  have h := (log_le_of_mul_le (q := (23 / 500 : ℝ)) (z := (59 / 309 : ℝ)) (U := (-384889235149 / 125000000000 : ℝ)) 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  rw [xlx_neg]; unfold xlx; linarith

theorem rx9 : xlx (577 / 500 : ℝ) ≤ (41323057492811 / 250000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (577 / 500 : ℝ)) (z := (77 / 1077 : ℝ)) (U := (71617084043 / 500000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx10 : (878777657427 / 3906250000000 : ℝ) ≤ xlx (-(12 / 125) : ℝ) := by
  have h := (log_le_of_mul_le (q := (12 / 125 : ℝ)) (z := (67 / 317 : ℝ)) (U := (-292925885809 / 125000000000 : ℝ)) 4 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  rw [xlx_neg]; unfold xlx; linarith

theorem rx11 : xlx (1179 / 1000 : ℝ) ≤ (48535486703631 / 250000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (1179 / 1000 : ℝ)) (z := (179 / 2179 : ℝ)) (U := (41166655389 / 250000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx12 : (255547732506781 / 1000000000000000 : ℝ) ≤ xlx (-(121 / 1000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (121 / 1000 : ℝ)) (z := (117 / 367 : ℝ)) (U := (-2111964731461 / 1000000000000 : ℝ)) 4 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  rw [xlx_neg]; unfold xlx; linarith

theorem rx13 : (101239711619 / 4000000000000 : ℝ) ≤ xlx (41 / 40 : ℝ) := by
  have h := (le_log_of_mul_le (q := (41 / 40 : ℝ)) (z := (1 / 81 : ℝ)) (L := (2469261259 / 100000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  unfold xlx; linarith

theorem rx14 : xlx (1 / 40 : ℝ) ≤ (-(3688879452547 / 40000000000000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (1 / 40 : ℝ)) (z := (3 / 13 : ℝ)) (U := (-3688879452547 / 1000000000000 : ℝ)) 6 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx15 : xlx (609 / 1000 : ℝ) ≤ (-(75506409926577 / 250000000000000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (609 / 1000 : ℝ)) (z := (109 / 1109 : ℝ)) (U := (-123984252753 / 250000000000 : ℝ)) 1 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx16 : (-(7170095532337 / 20000000000000) : ℝ) ≤ xlx (227 / 500 : ℝ) := by
  have h := (le_log_of_le_mul (q := (227 / 500 : ℝ)) (z := (51 / 176 : ℝ)) (L := (-31586323931 / 40000000000 : ℝ)) 2 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  unfold xlx; linarith

theorem rx17 : xlx (1059 / 1000 : ℝ) ≤ (3035362277529 / 50000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (1059 / 1000 : ℝ)) (z := (59 / 2059 : ℝ)) (U := (2866253331 / 50000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx18 : (-(42394776329943 / 1000000000000000) : ℝ) ≤ xlx (9 / 1000 : ℝ) := by
  have h := (le_log_of_le_mul (q := (9 / 1000 : ℝ)) (z := (19 / 269 : ℝ)) (L := (-4710530703327 / 1000000000000 : ℝ)) 7 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  unfold xlx; linarith

theorem rx19 : xlx (271 / 250 : ℝ) ≤ (10929145858939 / 125000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (271 / 250 : ℝ)) (z := (21 / 521 : ℝ)) (U := (40328951509 / 500000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx20 : (2067583277591 / 31250000000000 : ℝ) ≤ xlx (-(2 / 125) : ℝ) := by
  have h := (log_le_of_mul_le (q := (2 / 125 : ℝ)) (z := (3 / 253 : ℝ)) (U := (-2067583277591 / 500000000000 : ℝ)) 6 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  rw [xlx_neg]; unfold xlx; linarith

theorem rx21 : xlx (1109 / 1000 : ℝ) ≤ (114735707581221 / 1000000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (1109 / 1000 : ℝ)) (z := (109 / 2109 : ℝ)) (U := (103458708369 / 1000000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx22 : (65480755825049 / 500000000000000 : ℝ) ≤ xlx (-(41 / 1000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (41 / 1000 : ℝ)) (z := (39 / 289 : ℝ)) (U := (-1597091605489 / 500000000000 : ℝ)) 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  rw [xlx_neg]; unfold xlx; linarith

theorem rx23 : xlx (1159 / 1000 : ℝ) ≤ (85509608545461 / 500000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (1159 / 1000 : ℝ)) (z := (159 / 2159 : ℝ)) (U := (73778782179 / 500000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx24 : (8724700607987 / 40000000000000 : ℝ) ≤ xlx (-(91 / 1000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (91 / 1000 : ℝ)) (z := (57 / 307 : ℝ)) (U := (-95875830857 / 40000000000 : ℝ)) 4 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  rw [xlx_neg]; unfold xlx; linarith

theorem rx25 : xlx (148 / 125 : ℝ) ≤ (3124622924547 / 15625000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (148 / 125 : ℝ)) (z := (23 / 273 : ℝ)) (U := (84449268231 / 500000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx26 : (62470787508297 / 250000000000000 : ℝ) ≤ xlx (-(29 / 250) : ℝ) := by
  have h := (log_le_of_mul_le (q := (29 / 250 : ℝ)) (z := (107 / 357 : ℝ)) (U := (-2154165086493 / 1000000000000 : ℝ)) 4 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  rw [xlx_neg]; unfold xlx; linarith

theorem rx27 : (29416493099679 / 1000000000000000 : ℝ) ≤ xlx (1029 / 1000 : ℝ) := by
  have h := (le_log_of_mul_le (q := (1029 / 1000 : ℝ)) (z := (29 / 2029 : ℝ)) (L := (28587456851 / 1000000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  unfold xlx; linarith

theorem rx28 : xlx (29 / 1000 : ℝ) ≤ (-(102673323965697 / 1000000000000000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (29 / 1000 : ℝ)) (z := (107 / 357 : ℝ)) (U := (-3540459447093 / 1000000000000 : ℝ)) 6 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx29 : xlx (123 / 200 : ℝ) ≤ (-(11958872068509 / 40000000000000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (123 / 200 : ℝ)) (z := (23 / 223 : ℝ)) (U := (-97226602183 / 200000000000 : ℝ)) 1 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx30 : (-(8935640913717 / 25000000000000) : ℝ) ≤ xlx (459 / 1000 : ℝ) := by
  have h := (le_log_of_le_mul (q := (459 / 1000 : ℝ)) (z := (209 / 709 : ℝ)) (L := (-19467627263 / 25000000000 : ℝ)) 2 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  unfold xlx; linarith

theorem rx31 : xlx (213 / 200 : ℝ) ≤ (6706816110753 / 100000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (213 / 200 : ℝ)) (z := (13 / 413 : ℝ)) (U := (31487399581 / 500000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx32 : (-(12599115390951 / 200000000000000) : ℝ) ≤ xlx (3 / 200 : ℝ) := by
  have h := (le_log_of_le_mul (q := (3 / 200 : ℝ)) (z := (23 / 73 : ℝ)) (L := (-4199705130317 / 1000000000000 : ℝ)) 7 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  unfold xlx; linarith

theorem rx33 : xlx (109 / 100 : ℝ) ≤ (4696684445189 / 50000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (109 / 100 : ℝ)) (z := (9 / 209 : ℝ)) (U := (43088848121 / 500000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx34 : (575646273021 / 12500000000000 : ℝ) ≤ xlx (-(1 / 100) : ℝ) := by
  have h := (log_le_of_mul_le (q := (1 / 100 : ℝ)) (z := (7 / 57 : ℝ)) (U := (-575646273021 / 125000000000 : ℝ)) 7 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  rw [xlx_neg]; unfold xlx; linarith

theorem rx35 : xlx (223 / 200 : ℝ) ≤ (24274532295599 / 200000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (223 / 200 : ℝ)) (z := (23 / 423 : ℝ)) (U := (108854404913 / 1000000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx36 : (366669539271 / 3125000000000 : ℝ) ≤ xlx (-(7 / 200) : ℝ) := by
  have h := (log_le_of_mul_le (q := (7 / 200 : ℝ)) (z := (3 / 53 : ℝ)) (U := (-52381362753 / 15625000000 : ℝ)) 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  rw [xlx_neg]; unfold xlx; linarith

theorem rx37 : xlx (233 / 200 : ℝ) ≤ (17792006637597 / 100000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (233 / 200 : ℝ)) (z := (33 / 433 : ℝ)) (U := (76360543509 / 500000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx38 : (10476692091171 / 50000000000000 : ℝ) ≤ xlx (-(17 / 200) : ℝ) := by
  have h := (log_le_of_mul_le (q := (17 / 200 : ℝ)) (z := (9 / 59 : ℝ)) (U := (-616276005363 / 250000000000 : ℝ)) 4 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  rw [xlx_neg]; unfold xlx; linarith

theorem rx39 : xlx (119 / 100 : ℝ) ≤ (5175110886939 / 25000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (119 / 100 : ℝ)) (z := (19 / 219 : ℝ)) (U := (43488326781 / 250000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx40 : (3035003004077 / 12500000000000 : ℝ) ≤ xlx (-(11 / 100) : ℝ) := by
  have h := (log_le_of_mul_le (q := (11 / 100 : ℝ)) (z := (19 / 69 : ℝ)) (U := (-275909364007 / 125000000000 : ℝ)) 4 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  rw [xlx_neg]; unfold xlx; linarith

theorem rx41 : (8642889618231 / 250000000000000 : ℝ) ≤ xlx (517 / 500 : ℝ) := by
  have h := (le_log_of_mul_le (q := (517 / 500 : ℝ)) (z := (17 / 1017 : ℝ)) (L := (16717388043 / 500000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  unfold xlx; linarith

theorem rx42 : xlx (17 / 500 : ℝ) ≤ (-(28741855401061 / 250000000000000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (17 / 500 : ℝ)) (z := (11 / 261 : ℝ)) (U := (-1690697376533 / 500000000000 : ℝ)) 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx43 : xlx (1243 / 2000 : ℝ) ≤ (-(591194874139353 / 2000000000000000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (1243 / 2000 : ℝ)) (z := (243 / 2243 : ℝ)) (U := (-475619367771 / 1000000000000 : ℝ)) 1 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx44 : (-(7121176482183 / 20000000000000) : ℝ) ≤ xlx (93 / 200 : ℝ) := by
  have h := (le_log_of_le_mul (q := (93 / 200 : ℝ)) (z := (43 / 143 : ℝ)) (L := (-76571790131 / 100000000000 : ℝ)) 2 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  unfold xlx; linarith

theorem rx45 : xlx (2143 / 2000 : ℝ) ≤ (36998646375569 / 500000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (2143 / 2000 : ℝ)) (z := (143 / 4143 : ℝ)) (U := (17264883983 / 250000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx46 : (-(33021440169537 / 400000000000000) : ℝ) ≤ xlx (43 / 2000 : ℝ) := by
  have h := (le_log_of_le_mul (q := (43 / 2000 : ℝ)) (z := (47 / 297 : ℝ)) (L := (-767940469059 / 200000000000 : ℝ)) 6 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  unfold xlx; linarith

theorem rx47 : xlx (2193 / 2000 : ℝ) ≤ (50506593126267 / 500000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (2193 / 2000 : ℝ)) (z := (193 / 4193 : ℝ)) (U := (23030822219 / 250000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx48 : (39584946155993 / 2000000000000000 : ℝ) ≤ xlx (-(7 / 2000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (7 / 2000 : ℝ)) (z := (99 / 349 : ℝ)) (U := (-5654992307999 / 1000000000000 : ℝ)) 9 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  rw [xlx_neg]; unfold xlx; linarith

theorem rx49 : xlx (2243 / 2000 : ℝ) ≤ (257198249177897 / 2000000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (2243 / 2000 : ℝ)) (z := (243 / 4243 : ℝ)) (U := (114667074979 / 1000000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx50 : (1267484486409 / 12500000000000 : ℝ) ≤ xlx (-(57 / 2000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (57 / 2000 : ℝ)) (z := (103 / 353 : ℝ)) (U := (-22236569937 / 6250000000 : ℝ)) 6 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  rw [xlx_neg]; unfold xlx; linarith

theorem rx51 : xlx (2343 / 2000 : ℝ) ≤ (185430852858669 / 1000000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (2343 / 2000 : ℝ)) (z := (343 / 4343 : ℝ)) (U := (79142489483 / 500000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx52 : (399511094545021 / 2000000000000000 : ℝ) ≤ xlx (-(157 / 2000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (157 / 2000 : ℝ)) (z := (16 / 141 : ℝ)) (U := (-2544656653153 / 1000000000000 : ℝ)) 4 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  rw [xlx_neg]; unfold xlx; linarith

theorem rx53 : xlx (2393 / 2000 : ℝ) ≤ (429305703682231 / 2000000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (2393 / 2000 : ℝ)) (z := (393 / 4393 : ℝ)) (U := (179400628367 / 1000000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx54 : (469514018700333 / 2000000000000000 : ℝ) ≤ xlx (-(207 / 2000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (207 / 2000 : ℝ)) (z := (41 / 166 : ℝ)) (U := (-2268183665219 / 1000000000000 : ℝ)) 4 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  rw [xlx_neg]; unfold xlx; linarith

theorem rx55 : (509869270989 / 12500000000000 : ℝ) ≤ xlx (26 / 25 : ℝ) := by
  have h := (le_log_of_mul_le (q := (26 / 25 : ℝ)) (z := (1 / 51 : ℝ)) (L := (39220713153 / 1000000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  unfold xlx; linarith

theorem rx56 : xlx (1 / 25 : ℝ) ≤ (-(201179738973 / 1562500000000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (1 / 25 : ℝ)) (z := (7 / 57 : ℝ)) (U := (-201179738973 / 62500000000 : ℝ)) 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx57 : xlx (5 / 8 : ℝ) ≤ (-(94000725797 / 320000000000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (5 / 8 : ℝ)) (z := (1 / 9 : ℝ)) (U := (-94000725797 / 200000000000 : ℝ)) 1 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx58 : (-(354490774637903 / 1000000000000000) : ℝ) ≤ xlx (943 / 2000 : ℝ) := by
  have h := (le_log_of_le_mul (q := (943 / 2000 : ℝ)) (z := (443 / 1443 : ℝ)) (L := (-375918106721 / 500000000000 : ℝ)) 2 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  unfold xlx; linarith

theorem rx59 : xlx (43 / 40 : ℝ) ≤ (155489422397 / 2000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (43 / 40 : ℝ)) (z := (3 / 83 : ℝ)) (U := (3616033079 / 50000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx60 : (-(922219864101 / 10000000000000) : ℝ) ≤ xlx (1 / 40 : ℝ) := by
  have h := (le_log_of_le_mul (q := (1 / 40 : ℝ)) (z := (3 / 13 : ℝ)) (L := (-922219864101 / 250000000000 : ℝ)) 6 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  unfold xlx; linarith

theorem rx61 : xlx (11 / 10 : ℝ) ≤ (209682395571 / 2000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (11 / 10 : ℝ)) (z := (1 / 21 : ℝ)) (U := (19062035961 / 200000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx62 : 0 ≤ xlx 0 := by simp [xlx]

theorem rx63 : xlx (9 / 8 : ℝ) ≤ (1060047320913 / 8000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (9 / 8 : ℝ)) (z := (1 / 17 : ℝ)) (U := (117783035657 / 1000000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx64 : (3688879452547 / 40000000000000 : ℝ) ≤ xlx (-(1 / 40) : ℝ) := by
  have h := (log_le_of_mul_le (q := (1 / 40 : ℝ)) (z := (3 / 13 : ℝ)) (U := (-3688879452547 / 1000000000000 : ℝ)) 6 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  rw [xlx_neg]; unfold xlx; linarith

theorem rx65 : xlx (47 / 40 : ℝ) ≤ (7579602937059 / 40000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (47 / 40 : ℝ)) (z := (7 / 87 : ℝ)) (U := (161268147597 / 1000000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx66 : (3885400746609 / 20000000000000 : ℝ) ≤ xlx (-(3 / 40) : ℝ) := by
  have h := (log_le_of_mul_le (q := (3 / 40 : ℝ)) (z := (1 / 11 : ℝ)) (U := (-1295133582203 / 500000000000 : ℝ)) 4 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  rw [xlx_neg]; unfold xlx; linarith

theorem rx67 : xlx (6 / 5 : ℝ) ≤ (273482335191 / 1250000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (6 / 5 : ℝ)) (z := (1 / 11 : ℝ)) (U := (91160778397 / 500000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx68 : (2302585091947 / 10000000000000 : ℝ) ≤ xlx (-(1 / 10) : ℝ) := by
  have h := (log_le_of_mul_le (q := (1 / 10 : ℝ)) (z := (3 / 13 : ℝ)) (U := (-2302585091947 / 1000000000000 : ℝ)) 4 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  rw [xlx_neg]; unfold xlx; linarith

theorem rx69 : (95129493255979 / 2000000000000000 : ℝ) ≤ xlx (2093 / 2000 : ℝ) := by
  have h := (le_log_of_mul_le (q := (2093 / 2000 : ℝ)) (z := (93 / 4093 : ℝ)) (L := (45451262903 / 1000000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  unfold xlx; linarith

theorem rx70 : xlx (93 / 2000 : ℝ) ≤ (-(8917255492287 / 62500000000000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (93 / 2000 : ℝ)) (z := (61 / 311 : ℝ)) (U := (-95884467659 / 31250000000 : ℝ)) 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx71 : xlx (631 / 1000 : ℝ) ≤ (-(14527179080479 / 50000000000000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (631 / 1000 : ℝ)) (z := (131 / 1131 : ℝ)) (U := (-23022470809 / 50000000000 : ℝ)) 1 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx72 : (-(7072184911671 / 20000000000000) : ℝ) ≤ xlx (19 / 40 : ℝ) := by
  have h := (le_log_of_le_mul (q := (19 / 40 : ℝ)) (z := (9 / 29 : ℝ)) (L := (-372220258509 / 500000000000 : ℝ)) 2 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  unfold xlx; linarith

theorem rx73 : xlx (1081 / 1000 : ℝ) ≤ (42097674144649 / 500000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (1081 / 1000 : ℝ)) (z := (81 / 2081 : ℝ)) (U := (38943269329 / 500000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx74 : (-(107686813225329 / 1000000000000000) : ℝ) ≤ xlx (31 / 1000 : ℝ) := by
  have h := (le_log_of_le_mul (q := (31 / 1000 : ℝ)) (z := (123 / 373 : ℝ)) (L := (-3473768168559 / 1000000000000 : ℝ)) 6 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  unfold xlx; linarith

theorem rx75 : xlx (553 / 500 : ℝ) ≤ (55714696414853 / 500000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (553 / 500 : ℝ)) (z := (53 / 1053 : ℝ)) (U := (100749903101 / 1000000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx76 : (-(1918498429479 / 62500000000000) : ℝ) ≤ xlx (3 / 500 : ℝ) := by
  have h := (le_log_of_le_mul (q := (3 / 500 : ℝ)) (z := (67 / 317 : ℝ)) (L := (-639499476493 / 125000000000 : ℝ)) 8 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  unfold xlx; linarith

theorem rx77 : xlx (1131 / 1000 : ℝ) ≤ (69614292479277 / 500000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (1131 / 1000 : ℝ)) (z := (131 / 2131 : ℝ)) (U := (61551098567 / 500000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx78 : (4706438104179 / 62500000000000 : ℝ) ≤ xlx (-(19 / 1000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (19 / 1000 : ℝ)) (z := (27 / 277 : ℝ)) (U := (-247707268641 / 62500000000 : ℝ)) 6 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  rw [xlx_neg]; unfold xlx; linarith

theorem rx79 : xlx (1181 / 1000 : ℝ) ≤ (3069890241439 / 15625000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (1181 / 1000 : ℝ)) (z := (181 / 2181 : ℝ)) (U := (2599399019 / 15625000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx80 : (36896353072161 / 200000000000000 : ℝ) ≤ xlx (-(69 / 1000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (69 / 1000 : ℝ)) (z := (13 / 263 : ℝ)) (U := (-534729754669 / 200000000000 : ℝ)) 4 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  rw [xlx_neg]; unfold xlx; linarith

theorem rx81 : xlx (603 / 500 : ℝ) ≤ (22589477255583 / 100000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (603 / 500 : ℝ)) (z := (103 / 1103 : ℝ)) (U := (37461819661 / 200000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx82 : (111129643296537 / 500000000000000 : ℝ) ≤ xlx (-(47 / 500) : ℝ) := by
  have h := (log_le_of_mul_le (q := (47 / 500 : ℝ)) (z := (63 / 313 : ℝ)) (U := (-2364460495671 / 1000000000000 : ℝ)) 4 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  rw [xlx_neg]; unfold xlx; linarith

theorem rx83 : (1024593447549 / 20000000000000 : ℝ) ≤ xlx (21 / 20 : ℝ) := by
  have h := (le_log_of_mul_le (q := (21 / 20 : ℝ)) (z := (1 / 41 : ℝ)) (L := (48790164169 / 1000000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  unfold xlx; linarith

theorem rx84 : xlx (1 / 20 : ℝ) ≤ (-(2995732272247 / 20000000000000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (1 / 20 : ℝ)) (z := (3 / 13 : ℝ)) (U := (-2995732272247 / 1000000000000 : ℝ)) 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx85 : xlx (637 / 1000 : ℝ) ≤ (-(5745556838931 / 20000000000000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (637 / 1000 : ℝ)) (z := (137 / 1137 : ℝ)) (U := (-9019712463 / 20000000000 : ℝ)) 1 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx86 : (-(352038157889821 / 1000000000000000) : ℝ) ≤ xlx (481 / 1000 : ℝ) := by
  have h := (le_log_of_le_mul (q := (481 / 1000 : ℝ)) (z := (231 / 731 : ℝ)) (L := (-731888062141 / 1000000000000 : ℝ)) 2 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  unfold xlx; linarith

theorem rx87 : xlx (1087 / 1000 : ℝ) ≤ (4533964402409 / 50000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (1087 / 1000 : ℝ)) (z := (87 / 2087 : ℝ)) (U := (4171080407 / 50000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx88 : (-(121982982598943 / 1000000000000000) : ℝ) ≤ xlx (37 / 1000 : ℝ) := by
  have h := (le_log_of_le_mul (q := (37 / 1000 : ℝ)) (z := (23 / 273 : ℝ)) (L := (-3296837367539 / 1000000000000 : ℝ)) 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  unfold xlx; linarith

theorem rx89 : xlx (139 / 125 : ℝ) ≤ (14756267220231 / 125000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (139 / 125 : ℝ)) (z := (7 / 132 : ℝ)) (U := (106160195829 / 1000000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx90 : (-(1658568236679 / 31250000000000) : ℝ) ≤ xlx (3 / 250 : ℝ) := by
  have h := (le_log_of_le_mul (q := (3 / 250 : ℝ)) (z := (67 / 317 : ℝ)) (L := (-552856078893 / 125000000000 : ℝ)) 7 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  unfold xlx; linarith

theorem rx91 : xlx (1137 / 1000 : ℝ) ≤ (145983085192353 / 1000000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (1137 / 1000 : ℝ)) (z := (137 / 2137 : ℝ)) (U := (128393214769 / 1000000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx92 : (176426490487 / 3125000000000 : ℝ) ≤ xlx (-(13 / 1000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (13 / 1000 : ℝ)) (z := (83 / 333 : ℝ)) (U := (-13571268499 / 3125000000 : ℝ)) 7 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  rw [xlx_neg]; unfold xlx; linarith

theorem rx93 : xlx (1187 / 1000 : ℝ) ≤ (50871590062609 / 250000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (1187 / 1000 : ℝ)) (z := (187 / 2187 : ℝ)) (U := (42857278907 / 250000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx94 : (3483421894953 / 20000000000000 : ℝ) ≤ xlx (-(63 / 1000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (63 / 1000 : ℝ)) (z := (1 / 251 : ℝ)) (U := (-55292411031 / 20000000000 : ℝ)) 4 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  rw [xlx_neg]; unfold xlx; linarith

theorem rx95 : xlx (303 / 250 : ℝ) ≤ (1820574436167 / 7812500000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (303 / 250 : ℝ)) (z := (53 / 553 : ℝ)) (U := (6008496489 / 31250000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx96 : (3341825387263 / 15625000000000 : ℝ) ≤ xlx (-(11 / 125) : ℝ) := by
  have h := (log_le_of_mul_le (q := (11 / 125 : ℝ)) (z := (51 / 301 : ℝ)) (U := (-303802307933 / 125000000000 : ℝ)) 4 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  rw [xlx_neg]; unfold xlx; linarith

theorem rx97 : (449527528593 / 7812500000000 : ℝ) ≤ xlx (132 / 125 : ℝ) := by
  have h := (le_log_of_mul_le (q := (132 / 125 : ℝ)) (z := (7 / 257 : ℝ)) (L := (13622046321 / 250000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  unfold xlx; linarith

theorem rx98 : xlx (7 / 125 : ℝ) ≤ (-(20176825107593 / 125000000000000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (7 / 125 : ℝ)) (z := (99 / 349 : ℝ)) (U := (-2882403586799 / 1000000000000 : ℝ)) 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx99 : xlx (643 / 1000 : ℝ) ≤ (-(70988896633303 / 250000000000000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (643 / 1000 : ℝ)) (z := (143 / 1143 : ℝ)) (U := (-110402638621 / 250000000000 : ℝ)) 1 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx100 : (-(70078445105103 / 200000000000000) : ℝ) ≤ xlx (487 / 1000 : ℝ) := by
  have h := (le_log_of_le_mul (q := (487 / 1000 : ℝ)) (z := (237 / 737 : ℝ)) (L := (-143898244569 / 200000000000 : ℝ)) 2 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  unfold xlx; linarith

theorem rx101 : xlx (1093 / 1000 : ℝ) ≤ (19439269330027 / 200000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (1093 / 1000 : ℝ)) (z := (93 / 2093 : ℝ)) (U := (17785241839 / 200000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx102 : (-(27060374414657 / 200000000000000) : ℝ) ≤ xlx (43 / 1000 : ℝ) := by
  have h := (le_log_of_le_mul (q := (43 / 1000 : ℝ)) (z := (47 / 297 : ℝ)) (L := (-629311032899 / 200000000000 : ℝ)) 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  unfold xlx; linarith

theorem rx103 : xlx (559 / 500 : ℝ) ≤ (62351628475747 / 500000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (559 / 500 : ℝ)) (z := (59 / 1059 : ℝ)) (U := (111541374733 / 1000000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx104 : (-(36156451702743 / 500000000000000) : ℝ) ≤ xlx (9 / 500 : ℝ) := by
  have h := (le_log_of_le_mul (q := (9 / 500 : ℝ)) (z := (19 / 269 : ℝ)) (L := (-4017383522527 / 1000000000000 : ℝ)) 6 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  unfold xlx; linarith

theorem rx105 : xlx (1143 / 1000 : ℝ) ≤ (152769247841259 / 1000000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (1143 / 1000 : ℝ)) (z := (143 / 2143 : ℝ)) (U := (133656384813 / 1000000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx106 : (34732915893893 / 1000000000000000 : ℝ) ≤ xlx (-(7 / 1000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (7 / 1000 : ℝ)) (z := (99 / 349 : ℝ)) (U := (-4961845127699 / 1000000000000 : ℝ)) 8 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  rw [xlx_neg]; unfold xlx; linarith

theorem rx107 : xlx (1193 / 1000 : ℝ) ≤ (52632518434347 / 250000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (1193 / 1000 : ℝ)) (z := (193 / 2193 : ℝ)) (U := (44117785779 / 250000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx108 : (8164406427417 / 50000000000000 : ℝ) ≤ xlx (-(57 / 1000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (57 / 1000 : ℝ)) (z := (103 / 353 : ℝ)) (U := (-143235200481 / 50000000000 : ℝ)) 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  rw [xlx_neg]; unfold xlx; linarith

theorem rx109 : xlx (609 / 500 : ℝ) ≤ (15012624137049 / 62500000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (609 / 500 : ℝ)) (z := (109 / 1109 : ℝ)) (U := (24651271161 / 125000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx110 : (51271238628899 / 250000000000000 : ℝ) ≤ xlx (-(41 / 500) : ℝ) := by
  have h := (log_le_of_mul_le (q := (41 / 500 : ℝ)) (z := (39 / 289 : ℝ)) (U := (-1250518015339 / 500000000000 : ℝ)) 4 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  rw [xlx_neg]; unfold xlx; linarith

theorem rx111 : (31941733016889 / 500000000000000 : ℝ) ≤ xlx (531 / 500 : ℝ) := by
  have h := (le_log_of_mul_le (q := (531 / 500 : ℝ)) (z := (31 / 1031 : ℝ)) (L := (60153922819 / 1000000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  unfold xlx; linarith

theorem rx112 : xlx (31 / 500 : ℝ) ≤ (-(21549811906397 / 125000000000000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (31 / 500 : ℝ)) (z := (123 / 373 : ℝ)) (U := (-695155222787 / 250000000000 : ℝ)) 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx113 : xlx (129 / 200 : ℝ) ≤ (-(28283570044227 / 100000000000000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (129 / 200 : ℝ)) (z := (29 / 229 : ℝ)) (U := (-219252480963 / 500000000000 : ℝ)) 1 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx114 : (-(34867237092557 / 100000000000000) : ℝ) ≤ xlx (493 / 1000 : ℝ) := by
  have h := (le_log_of_le_mul (q := (493 / 1000 : ℝ)) (z := (243 / 743 : ℝ)) (L := (-70724618849 / 100000000000 : ℝ)) 2 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  unfold xlx; linarith

theorem rx115 : xlx (219 / 200 : ℝ) ≤ (19875205555911 / 200000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (219 / 200 : ℝ)) (z := (19 / 419 : ℝ)) (U := (90754363269 / 1000000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx116 : (-(13954917557007 / 100000000000000) : ℝ) ≤ xlx (9 / 200 : ℝ) := by
  have h := (le_log_of_le_mul (q := (9 / 200 : ℝ)) (z := (11 / 61 : ℝ)) (L := (-1550546395223 / 500000000000 : ℝ)) 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  unfold xlx; linarith

theorem rx117 : xlx (28 / 25 : ℝ) ≤ (198325199289 / 1562500000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (28 / 25 : ℝ)) (z := (3 / 53 : ℝ)) (U := (28332171327 / 250000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx118 : (-(3912023006869 / 50000000000000) : ℝ) ≤ xlx (1 / 50 : ℝ) := by
  have h := (le_log_of_le_mul (q := (1 / 50 : ℝ)) (z := (7 / 57 : ℝ)) (L := (-3912023006869 / 1000000000000 : ℝ)) 6 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  unfold xlx; linarith

theorem rx119 : xlx (229 / 200 : ℝ) ≤ (31007661874603 / 200000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (229 / 200 : ℝ)) (z := (29 / 429 : ℝ)) (U := (135404637007 / 1000000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx120 : (1324579341117 / 50000000000000 : ℝ) ≤ xlx (-(1 / 200) : ℝ) := by
  have h := (log_le_of_mul_le (q := (1 / 200 : ℝ)) (z := (7 / 57 : ℝ)) (U := (-1324579341117 / 250000000000 : ℝ)) 8 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  rw [xlx_neg]; unfold xlx; linarith

theorem rx121 : xlx (239 / 200 : ℝ) ≤ (5322117288347 / 25000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (239 / 200 : ℝ)) (z := (39 / 439 : ℝ)) (U := (22268273173 / 125000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx122 : (7976160753979 / 50000000000000 : ℝ) ≤ xlx (-(11 / 200) : ℝ) := by
  have h := (log_le_of_mul_le (q := (11 / 200 : ℝ)) (z := (19 / 69 : ℝ)) (U := (-725105523089 / 250000000000 : ℝ)) 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  rw [xlx_neg]; unfold xlx; linarith

theorem rx123 : xlx (61 / 50 : ℝ) ≤ (6064951191753 / 25000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (61 / 50 : ℝ)) (z := (11 / 111 : ℝ)) (U := (99425429373 / 500000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

theorem rx124 : (631432160817 / 3125000000000 : ℝ) ≤ xlx (-(2 / 25) : ℝ) := by
  have h := (log_le_of_mul_le (q := (2 / 25 : ℝ)) (z := (7 / 57 : ℝ)) (U := (-631432160817 / 250000000000 : ℝ)) 4 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  rw [xlx_neg]; unfold xlx; linarith

theorem rx125 : (8782663361823 / 125000000000000 : ℝ) ≤ xlx (267 / 250 : ℝ) := by
  have h := (le_log_of_mul_le (q := (267 / 250 : ℝ)) (z := (17 / 517 : ℝ)) (L := (32893870269 / 500000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  unfold xlx; linarith

theorem rx126 : xlx (17 / 250 : ℝ) ≤ (-(22850104368511 / 125000000000000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (17 / 250 : ℝ)) (z := (11 / 261 : ℝ)) (U := (-1344123786383 / 500000000000 : ℝ)) 4 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  unfold xlx; linarith

/-! ## The cells -/

/-- Cell `[1 / 40, 29 / 1000]` (certified bound `-0.725447`). -/
theorem real_cell_1 (ξ : ℝ) (h1 : (1 / 40 : ℝ) ≤ ξ) (h2 : ξ ≤ (29 / 1000 : ℝ)) : Preal ξ ≤ -18 / 25 := by
  have : xlx (ξ + 23 / 40) ≤ xlx (151 / 250 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (9 / 20 : ℝ) ≤ xlx (ξ + 17 / 40) := xlx_mono (by norm_num) (by linarith)
  have : xlx (ξ + 41 / 40) ≤ xlx (527 / 500 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (1 / 250 : ℝ) ≤ xlx (ξ - 1 / 40) := xlx_anti_pos (by linarith) (by linarith) (by norm_num)
  have : xlx (ξ + 21 / 20) ≤ xlx (1079 / 1000 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (-(21 / 1000) : ℝ) ≤ xlx (ξ - 1 / 20) := xlx_anti_neg (by linarith) (by linarith) (by norm_num)
  have : xlx (ξ + 43 / 40) ≤ xlx (138 / 125 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (-(23 / 500) : ℝ) ≤ xlx (ξ - 3 / 40) := xlx_anti_neg (by linarith) (by linarith) (by norm_num)
  have : xlx (ξ + 9 / 8) ≤ xlx (577 / 500 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (-(12 / 125) : ℝ) ≤ xlx (ξ - 1 / 8) := xlx_anti_neg (by linarith) (by linarith) (by norm_num)
  have : xlx (ξ + 23 / 20) ≤ xlx (1179 / 1000 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (-(121 / 1000) : ℝ) ≤ xlx (ξ - 3 / 20) := xlx_anti_neg (by linarith) (by linarith) (by norm_num)
  have : xlx (41 / 40 : ℝ) ≤ xlx (ξ + 1) := xlx_mono (by norm_num) (by linarith)
  have : xlx (ξ) ≤ xlx (1 / 40 : ℝ) := xlx_anti_pos (by norm_num) (by linarith) (by linarith)
  unfold Preal
  linarith [rx1, rx2, rx3, rx4, rx5, rx6, rx7, rx8, rx9, rx10, rx11, rx12, rx13, rx14]

/-- Cell `[29 / 1000, 17 / 500]` (certified bound `-0.724919`). -/
theorem real_cell_2 (ξ : ℝ) (h1 : (29 / 1000 : ℝ) ≤ ξ) (h2 : ξ ≤ (17 / 500 : ℝ)) : Preal ξ ≤ -18 / 25 := by
  have : xlx (ξ + 23 / 40) ≤ xlx (609 / 1000 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (227 / 500 : ℝ) ≤ xlx (ξ + 17 / 40) := xlx_mono (by norm_num) (by linarith)
  have : xlx (ξ + 41 / 40) ≤ xlx (1059 / 1000 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (9 / 1000 : ℝ) ≤ xlx (ξ - 1 / 40) := xlx_anti_pos (by linarith) (by linarith) (by norm_num)
  have : xlx (ξ + 21 / 20) ≤ xlx (271 / 250 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (-(2 / 125) : ℝ) ≤ xlx (ξ - 1 / 20) := xlx_anti_neg (by linarith) (by linarith) (by norm_num)
  have : xlx (ξ + 43 / 40) ≤ xlx (1109 / 1000 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (-(41 / 1000) : ℝ) ≤ xlx (ξ - 3 / 40) := xlx_anti_neg (by linarith) (by linarith) (by norm_num)
  have : xlx (ξ + 9 / 8) ≤ xlx (1159 / 1000 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (-(91 / 1000) : ℝ) ≤ xlx (ξ - 1 / 8) := xlx_anti_neg (by linarith) (by linarith) (by norm_num)
  have : xlx (ξ + 23 / 20) ≤ xlx (148 / 125 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (-(29 / 250) : ℝ) ≤ xlx (ξ - 3 / 20) := xlx_anti_neg (by linarith) (by linarith) (by norm_num)
  have : xlx (1029 / 1000 : ℝ) ≤ xlx (ξ + 1) := xlx_mono (by norm_num) (by linarith)
  have : xlx (ξ) ≤ xlx (29 / 1000 : ℝ) := xlx_anti_pos (by norm_num) (by linarith) (by linarith)
  unfold Preal
  linarith [rx15, rx16, rx17, rx18, rx19, rx20, rx21, rx22, rx23, rx24, rx25, rx26, rx27, rx28]

/-- Cell `[17 / 500, 1 / 25]` (certified bound `-0.724205`). -/
theorem real_cell_3 (ξ : ℝ) (h1 : (17 / 500 : ℝ) ≤ ξ) (h2 : ξ ≤ (1 / 25 : ℝ)) : Preal ξ ≤ -18 / 25 := by
  have : xlx (ξ + 23 / 40) ≤ xlx (123 / 200 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (459 / 1000 : ℝ) ≤ xlx (ξ + 17 / 40) := xlx_mono (by norm_num) (by linarith)
  have : xlx (ξ + 41 / 40) ≤ xlx (213 / 200 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (3 / 200 : ℝ) ≤ xlx (ξ - 1 / 40) := xlx_anti_pos (by linarith) (by linarith) (by norm_num)
  have : xlx (ξ + 21 / 20) ≤ xlx (109 / 100 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (-(1 / 100) : ℝ) ≤ xlx (ξ - 1 / 20) := xlx_anti_neg (by linarith) (by linarith) (by norm_num)
  have : xlx (ξ + 43 / 40) ≤ xlx (223 / 200 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (-(7 / 200) : ℝ) ≤ xlx (ξ - 3 / 40) := xlx_anti_neg (by linarith) (by linarith) (by norm_num)
  have : xlx (ξ + 9 / 8) ≤ xlx (233 / 200 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (-(17 / 200) : ℝ) ≤ xlx (ξ - 1 / 8) := xlx_anti_neg (by linarith) (by linarith) (by norm_num)
  have : xlx (ξ + 23 / 20) ≤ xlx (119 / 100 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (-(11 / 100) : ℝ) ≤ xlx (ξ - 3 / 20) := xlx_anti_neg (by linarith) (by linarith) (by norm_num)
  have : xlx (517 / 500 : ℝ) ≤ xlx (ξ + 1) := xlx_mono (by norm_num) (by linarith)
  have : xlx (ξ) ≤ xlx (17 / 500 : ℝ) := xlx_anti_pos (by norm_num) (by linarith) (by linarith)
  unfold Preal
  linarith [rx29, rx30, rx31, rx32, rx33, rx34, rx35, rx36, rx37, rx38, rx39, rx40, rx41, rx42]

/-- Cell `[1 / 25, 93 / 2000]` (certified bound `-0.726263`). -/
theorem real_cell_4 (ξ : ℝ) (h1 : (1 / 25 : ℝ) ≤ ξ) (h2 : ξ ≤ (93 / 2000 : ℝ)) : Preal ξ ≤ -18 / 25 := by
  have : xlx (ξ + 23 / 40) ≤ xlx (1243 / 2000 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (93 / 200 : ℝ) ≤ xlx (ξ + 17 / 40) := xlx_mono (by norm_num) (by linarith)
  have : xlx (ξ + 41 / 40) ≤ xlx (2143 / 2000 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (43 / 2000 : ℝ) ≤ xlx (ξ - 1 / 40) := xlx_anti_pos (by linarith) (by linarith) (by norm_num)
  have : xlx (ξ + 21 / 20) ≤ xlx (2193 / 2000 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (-(7 / 2000) : ℝ) ≤ xlx (ξ - 1 / 20) := xlx_anti_neg (by linarith) (by linarith) (by norm_num)
  have : xlx (ξ + 43 / 40) ≤ xlx (2243 / 2000 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (-(57 / 2000) : ℝ) ≤ xlx (ξ - 3 / 40) := xlx_anti_neg (by linarith) (by linarith) (by norm_num)
  have : xlx (ξ + 9 / 8) ≤ xlx (2343 / 2000 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (-(157 / 2000) : ℝ) ≤ xlx (ξ - 1 / 8) := xlx_anti_neg (by linarith) (by linarith) (by norm_num)
  have : xlx (ξ + 23 / 20) ≤ xlx (2393 / 2000 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (-(207 / 2000) : ℝ) ≤ xlx (ξ - 3 / 20) := xlx_anti_neg (by linarith) (by linarith) (by norm_num)
  have : xlx (26 / 25 : ℝ) ≤ xlx (ξ + 1) := xlx_mono (by norm_num) (by linarith)
  have : xlx (ξ) ≤ xlx (1 / 25 : ℝ) := xlx_anti_pos (by norm_num) (by linarith) (by linarith)
  unfold Preal
  linarith [rx43, rx44, rx45, rx46, rx47, rx48, rx49, rx50, rx51, rx52, rx53, rx54, rx55, rx56]

/-- Cell `[93 / 2000, 1 / 20]` (certified bound `-0.781867`). -/
theorem real_cell_5 (ξ : ℝ) (h1 : (93 / 2000 : ℝ) ≤ ξ) (h2 : ξ ≤ (1 / 20 : ℝ)) : Preal ξ ≤ -18 / 25 := by
  have : xlx (ξ + 23 / 40) ≤ xlx (5 / 8 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (943 / 2000 : ℝ) ≤ xlx (ξ + 17 / 40) := xlx_mono (by norm_num) (by linarith)
  have : xlx (ξ + 41 / 40) ≤ xlx (43 / 40 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (1 / 40 : ℝ) ≤ xlx (ξ - 1 / 40) := xlx_anti_pos (by linarith) (by linarith) (by norm_num)
  have : xlx (ξ + 21 / 20) ≤ xlx (11 / 10 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (0 : ℝ) ≤ xlx (ξ - 1 / 20) := xlx_anti_neg (by linarith) (by linarith) (by norm_num)
  have : xlx (ξ + 43 / 40) ≤ xlx (9 / 8 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (-(1 / 40) : ℝ) ≤ xlx (ξ - 3 / 40) := xlx_anti_neg (by linarith) (by linarith) (by norm_num)
  have : xlx (ξ + 9 / 8) ≤ xlx (47 / 40 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (-(3 / 40) : ℝ) ≤ xlx (ξ - 1 / 8) := xlx_anti_neg (by linarith) (by linarith) (by norm_num)
  have : xlx (ξ + 23 / 20) ≤ xlx (6 / 5 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (-(1 / 10) : ℝ) ≤ xlx (ξ - 3 / 20) := xlx_anti_neg (by linarith) (by linarith) (by norm_num)
  have : xlx (2093 / 2000 : ℝ) ≤ xlx (ξ + 1) := xlx_mono (by norm_num) (by linarith)
  have : xlx (ξ) ≤ xlx (93 / 2000 : ℝ) := xlx_anti_pos (by norm_num) (by linarith) (by linarith)
  unfold Preal
  linarith [rx57, rx58, rx59, rx60, rx61, rx62, rx63, rx64, rx65, rx66, rx67, rx68, rx69, rx70]

/-- Cell `[1 / 20, 7 / 125]` (certified bound `-0.729472`). -/
theorem real_cell_6 (ξ : ℝ) (h1 : (1 / 20 : ℝ) ≤ ξ) (h2 : ξ ≤ (7 / 125 : ℝ)) : Preal ξ ≤ -18 / 25 := by
  have : xlx (ξ + 23 / 40) ≤ xlx (631 / 1000 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (19 / 40 : ℝ) ≤ xlx (ξ + 17 / 40) := xlx_mono (by norm_num) (by linarith)
  have : xlx (ξ + 41 / 40) ≤ xlx (1081 / 1000 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (31 / 1000 : ℝ) ≤ xlx (ξ - 1 / 40) := xlx_anti_pos (by linarith) (by linarith) (by norm_num)
  have : xlx (ξ + 21 / 20) ≤ xlx (553 / 500 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (3 / 500 : ℝ) ≤ xlx (ξ - 1 / 20) := xlx_anti_pos (by linarith) (by linarith) (by norm_num)
  have : xlx (ξ + 43 / 40) ≤ xlx (1131 / 1000 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (-(19 / 1000) : ℝ) ≤ xlx (ξ - 3 / 40) := xlx_anti_neg (by linarith) (by linarith) (by norm_num)
  have : xlx (ξ + 9 / 8) ≤ xlx (1181 / 1000 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (-(69 / 1000) : ℝ) ≤ xlx (ξ - 1 / 8) := xlx_anti_neg (by linarith) (by linarith) (by norm_num)
  have : xlx (ξ + 23 / 20) ≤ xlx (603 / 500 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (-(47 / 500) : ℝ) ≤ xlx (ξ - 3 / 20) := xlx_anti_neg (by linarith) (by linarith) (by norm_num)
  have : xlx (21 / 20 : ℝ) ≤ xlx (ξ + 1) := xlx_mono (by norm_num) (by linarith)
  have : xlx (ξ) ≤ xlx (1 / 20 : ℝ) := xlx_anti_pos (by norm_num) (by linarith) (by linarith)
  unfold Preal
  linarith [rx71, rx72, rx73, rx74, rx75, rx76, rx77, rx78, rx79, rx80, rx81, rx82, rx83, rx84]

/-- Cell `[7 / 125, 31 / 500]` (certified bound `-0.727179`). -/
theorem real_cell_7 (ξ : ℝ) (h1 : (7 / 125 : ℝ) ≤ ξ) (h2 : ξ ≤ (31 / 500 : ℝ)) : Preal ξ ≤ -18 / 25 := by
  have : xlx (ξ + 23 / 40) ≤ xlx (637 / 1000 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (481 / 1000 : ℝ) ≤ xlx (ξ + 17 / 40) := xlx_mono (by norm_num) (by linarith)
  have : xlx (ξ + 41 / 40) ≤ xlx (1087 / 1000 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (37 / 1000 : ℝ) ≤ xlx (ξ - 1 / 40) := xlx_anti_pos (by linarith) (by linarith) (by norm_num)
  have : xlx (ξ + 21 / 20) ≤ xlx (139 / 125 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (3 / 250 : ℝ) ≤ xlx (ξ - 1 / 20) := xlx_anti_pos (by linarith) (by linarith) (by norm_num)
  have : xlx (ξ + 43 / 40) ≤ xlx (1137 / 1000 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (-(13 / 1000) : ℝ) ≤ xlx (ξ - 3 / 40) := xlx_anti_neg (by linarith) (by linarith) (by norm_num)
  have : xlx (ξ + 9 / 8) ≤ xlx (1187 / 1000 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (-(63 / 1000) : ℝ) ≤ xlx (ξ - 1 / 8) := xlx_anti_neg (by linarith) (by linarith) (by norm_num)
  have : xlx (ξ + 23 / 20) ≤ xlx (303 / 250 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (-(11 / 125) : ℝ) ≤ xlx (ξ - 3 / 20) := xlx_anti_neg (by linarith) (by linarith) (by norm_num)
  have : xlx (132 / 125 : ℝ) ≤ xlx (ξ + 1) := xlx_mono (by norm_num) (by linarith)
  have : xlx (ξ) ≤ xlx (7 / 125 : ℝ) := xlx_anti_pos (by norm_num) (by linarith) (by linarith)
  unfold Preal
  linarith [rx85, rx86, rx87, rx88, rx89, rx90, rx91, rx92, rx93, rx94, rx95, rx96, rx97, rx98]

/-- Cell `[31 / 500, 17 / 250]` (certified bound `-0.721345`). -/
theorem real_cell_8 (ξ : ℝ) (h1 : (31 / 500 : ℝ) ≤ ξ) (h2 : ξ ≤ (17 / 250 : ℝ)) : Preal ξ ≤ -18 / 25 := by
  have : xlx (ξ + 23 / 40) ≤ xlx (643 / 1000 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (487 / 1000 : ℝ) ≤ xlx (ξ + 17 / 40) := xlx_mono (by norm_num) (by linarith)
  have : xlx (ξ + 41 / 40) ≤ xlx (1093 / 1000 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (43 / 1000 : ℝ) ≤ xlx (ξ - 1 / 40) := xlx_anti_pos (by linarith) (by linarith) (by norm_num)
  have : xlx (ξ + 21 / 20) ≤ xlx (559 / 500 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (9 / 500 : ℝ) ≤ xlx (ξ - 1 / 20) := xlx_anti_pos (by linarith) (by linarith) (by norm_num)
  have : xlx (ξ + 43 / 40) ≤ xlx (1143 / 1000 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (-(7 / 1000) : ℝ) ≤ xlx (ξ - 3 / 40) := xlx_anti_neg (by linarith) (by linarith) (by norm_num)
  have : xlx (ξ + 9 / 8) ≤ xlx (1193 / 1000 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (-(57 / 1000) : ℝ) ≤ xlx (ξ - 1 / 8) := xlx_anti_neg (by linarith) (by linarith) (by norm_num)
  have : xlx (ξ + 23 / 20) ≤ xlx (609 / 500 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (-(41 / 500) : ℝ) ≤ xlx (ξ - 3 / 20) := xlx_anti_neg (by linarith) (by linarith) (by norm_num)
  have : xlx (531 / 500 : ℝ) ≤ xlx (ξ + 1) := xlx_mono (by norm_num) (by linarith)
  have : xlx (ξ) ≤ xlx (31 / 500 : ℝ) := xlx_anti_pos (by norm_num) (by linarith) (by linarith)
  unfold Preal
  linarith [rx99, rx100, rx101, rx102, rx103, rx104, rx105, rx106, rx107, rx108, rx109, rx110, rx111, rx112]

/-- Cell `[17 / 250, 7 / 100]` (certified bound `-0.785994`). -/
theorem real_cell_9 (ξ : ℝ) (h1 : (17 / 250 : ℝ) ≤ ξ) (h2 : ξ ≤ (7 / 100 : ℝ)) : Preal ξ ≤ -18 / 25 := by
  have : xlx (ξ + 23 / 40) ≤ xlx (129 / 200 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (493 / 1000 : ℝ) ≤ xlx (ξ + 17 / 40) := xlx_mono (by norm_num) (by linarith)
  have : xlx (ξ + 41 / 40) ≤ xlx (219 / 200 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (9 / 200 : ℝ) ≤ xlx (ξ - 1 / 40) := xlx_anti_pos (by linarith) (by linarith) (by norm_num)
  have : xlx (ξ + 21 / 20) ≤ xlx (28 / 25 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (1 / 50 : ℝ) ≤ xlx (ξ - 1 / 20) := xlx_anti_pos (by linarith) (by linarith) (by norm_num)
  have : xlx (ξ + 43 / 40) ≤ xlx (229 / 200 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (-(1 / 200) : ℝ) ≤ xlx (ξ - 3 / 40) := xlx_anti_neg (by linarith) (by linarith) (by norm_num)
  have : xlx (ξ + 9 / 8) ≤ xlx (239 / 200 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (-(11 / 200) : ℝ) ≤ xlx (ξ - 1 / 8) := xlx_anti_neg (by linarith) (by linarith) (by norm_num)
  have : xlx (ξ + 23 / 20) ≤ xlx (61 / 50 : ℝ) := xlx_mono (by linarith) (by linarith)
  have : xlx (-(2 / 25) : ℝ) ≤ xlx (ξ - 3 / 20) := xlx_anti_neg (by linarith) (by linarith) (by norm_num)
  have : xlx (267 / 250 : ℝ) ≤ xlx (ξ + 1) := xlx_mono (by norm_num) (by linarith)
  have : xlx (ξ) ≤ xlx (17 / 250 : ℝ) := xlx_anti_pos (by norm_num) (by linarith) (by linarith)
  unfold Preal
  linarith [rx113, rx114, rx115, rx116, rx117, rx118, rx119, rx120, rx121, rx122, rx123, rx124, rx125, rx126]
/-- **(L-ii)** `Φ(ξ, 0) ≤ -18/25` on `[1/40, 7/100]`. -/
theorem Preal_le : ∀ ξ ∈ Set.Icc (1 / 40 : ℝ) (7 / 100), Preal ξ ≤ -18 / 25 := by
  rintro ξ ⟨h1, h2⟩
  rcases le_or_gt ξ (29 / 1000 : ℝ) with c1 | c1
  · exact real_cell_1 ξ (by linarith) c1
  rcases le_or_gt ξ (17 / 500 : ℝ) with c2 | c2
  · exact real_cell_2 ξ (by linarith) c2
  rcases le_or_gt ξ (1 / 25 : ℝ) with c3 | c3
  · exact real_cell_3 ξ (by linarith) c3
  rcases le_or_gt ξ (93 / 2000 : ℝ) with c4 | c4
  · exact real_cell_4 ξ (by linarith) c4
  rcases le_or_gt ξ (1 / 20 : ℝ) with c5 | c5
  · exact real_cell_5 ξ (by linarith) c5
  rcases le_or_gt ξ (7 / 125 : ℝ) with c6 | c6
  · exact real_cell_6 ξ (by linarith) c6
  rcases le_or_gt ξ (31 / 500 : ℝ) with c7 | c7
  · exact real_cell_7 ξ (by linarith) c7
  rcases le_or_gt ξ (17 / 250 : ℝ) with c8 | c8
  · exact real_cell_8 ξ (by linarith) c8
  exact real_cell_9 ξ (by linarith) h2

end Zeta2.Pair.Landscape
