import Zeta2Lean.Pair.Proofs.Landscape.VertBase

/-!
# (L-iii) The vertical line through the saddle: `Ψ(η) = Φ(7/100, η) - 2πη ≤ -18/25`, `0 < η ≤ 1`

**Certificate** (generated by `Landscape/gen/lean_vert.py`, exact rational arithmetic): four cells
`[0, 1/50]`, `[1/50, 1/20]`, `[1/20, 9/50]`, `[9/50, 1]`.  On a cell `[l, r]`,
`Ψ(η) ≤ Ψ(l) + (r - l) M` (`Psi_le_of_deriv`), where `M ≥ sup_{(l, r)} Ψ'` comes from the
monotonicity in `ζ` of every summand `s_j arctan(a_j/ζ)` of `Ψ' = dPsi` (evaluated at `l` or `r`;
at `l = 0` by `|arctan| < π/2`).  The values `Ψ(l)` are bounded from the rational `log`/`arctan`
certificates of `Numerics.lean` (`Lf_eq_pos`, `Lf_eq_neg`, `Lf_eq_zero`), and `π` by
`Real.pi_gt_d20`, `Real.pi_lt_d20`.  True maximum: `-0.78127` at `η ≈ 0.031`.
-/

set_option linter.style.longLine false

open Real

noncomputable section

namespace Zeta2.Pair.Landscape

/-! ## Certified values of `log`, `arctan` and `Lf` at the grid points -/

theorem vl1 : Real.log (16641 / 40000 : ℝ) ≤ (-(109626240479 / 125000000000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (16641 / 40000 : ℝ)) (z := (6641 / 26641 : ℝ)) (U := (-109626240479 / 125000000000 : ℝ)) 2 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem vf1 : Lf (129 / 200 : ℝ) (0 : ℝ) ≤ (0 : ℝ) * π + (-(46391785021791 / 50000000000000) : ℝ) := by
  rw [Lf_eq_zero (a := (129 / 200 : ℝ)) (Q := (16641 / 40000 : ℝ)) (by norm_num)]
  linarith [vl1]

theorem vl2 : (-(703197554029 / 500000000000) : ℝ) ≤ Real.log (9801 / 40000 : ℝ) := by
  have h := (le_log_of_le_mul (q := (9801 / 40000 : ℝ)) (z := (4801 / 14801 : ℝ)) (L := (-703197554029 / 500000000000 : ℝ)) 3 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  linarith

theorem vf2 : (0 : ℝ) * π + (-(168616557848871 / 200000000000000) : ℝ) ≤ Lf (99 / 200 : ℝ) (0 : ℝ) := by
  rw [Lf_eq_zero (a := (99 / 200 : ℝ)) (Q := (9801 / 40000 : ℝ)) (by norm_num)]
  linarith [vl2]

theorem vl3 : Real.log (47961 / 40000 : ℝ) ≤ (181508726537 / 1000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (47961 / 40000 : ℝ)) (z := (7961 / 87961 : ℝ)) (U := (181508726537 / 1000000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem vf3 : Lf (219 / 200 : ℝ) (0 : ℝ) ≤ (0 : ℝ) * π + (-(398249588888397 / 400000000000000) : ℝ) := by
  rw [Lf_eq_zero (a := (219 / 200 : ℝ)) (Q := (47961 / 40000 : ℝ)) (by norm_num)]
  linarith [vl3]

theorem vl4 : (-(1240437116117 / 200000000000) : ℝ) ≤ Real.log (81 / 40000 : ℝ) := by
  have h := (le_log_of_le_mul (q := (81 / 40000 : ℝ)) (z := (23 / 1273 : ℝ)) (L := (-1240437116117 / 200000000000 : ℝ)) 9 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  linarith

theorem vf4 : (0 : ℝ) * π + (-(14763934045053 / 80000000000000) : ℝ) ≤ Lf (9 / 200 : ℝ) (0 : ℝ) := by
  rw [Lf_eq_zero (a := (9 / 200 : ℝ)) (Q := (81 / 40000 : ℝ)) (by norm_num)]
  linarith [vl4]

theorem vl5 : Real.log (784 / 625 : ℝ) ≤ (45331474123 / 200000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (784 / 625 : ℝ)) (z := (159 / 1409 : ℝ)) (U := (45331474123 / 200000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem vf5 : Lf (28 / 25 : ℝ) (0 : ℝ) ≤ (0 : ℝ) * π + (-(2482679681139 / 2500000000000) : ℝ) := by
  rw [Lf_eq_zero (a := (28 / 25 : ℝ)) (Q := (784 / 625 : ℝ)) (by norm_num)]
  linarith [vl5]

theorem vl6 : (-(7824046015317 / 1000000000000) : ℝ) ≤ Real.log (1 / 2500 : ℝ) := by
  have h := (le_log_of_le_mul (q := (1 / 2500 : ℝ)) (z := (399 / 1649 : ℝ)) (L := (-7824046015317 / 1000000000000 : ℝ)) 12 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  linarith

theorem vf6 : (0 : ℝ) * π + (-(9824046015317 / 100000000000000) : ℝ) ≤ Lf (1 / 50 : ℝ) (0 : ℝ) := by
  rw [Lf_eq_zero (a := (1 / 50 : ℝ)) (Q := (1 / 2500 : ℝ)) (by norm_num)]
  linarith [vl6]

theorem vl7 : Real.log (52441 / 40000 : ℝ) ≤ (270809274013 / 1000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (52441 / 40000 : ℝ)) (z := (12441 / 92441 : ℝ)) (U := (270809274013 / 1000000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem vf7 : Lf (229 / 200 : ℝ) (0 : ℝ) ≤ (0 : ℝ) * π + (-(395984676251023 / 400000000000000) : ℝ) := by
  rw [Lf_eq_zero (a := (229 / 200 : ℝ)) (Q := (52441 / 40000 : ℝ)) (by norm_num)]
  linarith [vl7]

theorem vl8 : Real.log (1 / 40000 : ℝ) ≤ (-(10596634728923 / 1000000000000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (1 / 40000 : ℝ)) (z := (399 / 1649 : ℝ)) (U := (-10596634728923 / 1000000000000 : ℝ)) 16 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem vf8 : (0 : ℝ) * π + (12596634728923 / 400000000000000 : ℝ) ≤ Lf (-(1 / 200) : ℝ) (0 : ℝ) := by
  rw [Lf_eq_zero (a := (-(1 / 200) : ℝ)) (Q := (1 / 40000 : ℝ)) (by norm_num)]
  linarith [vl8]

theorem vl9 : Real.log (57121 / 40000 : ℝ) ≤ (22268273173 / 62500000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (57121 / 40000 : ℝ)) (z := (17121 / 97121 : ℝ)) (U := (22268273173 / 62500000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem vf9 : Lf (239 / 200 : ℝ) (0 : ℝ) ≤ (0 : ℝ) * π + (-(24552882711653 / 25000000000000) : ℝ) := by
  rw [Lf_eq_zero (a := (239 / 200 : ℝ)) (Q := (57121 / 40000 : ℝ)) (by norm_num)]
  linarith [vl9]

theorem vl10 : Real.log (121 / 40000 : ℝ) ≤ (-(5800844185157 / 1000000000000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (121 / 40000 : ℝ)) (z := (343 / 1593 : ℝ)) (U := (-5800844185157 / 1000000000000 : ℝ)) 9 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem vf10 : (0 : ℝ) * π + (85809286036727 / 400000000000000 : ℝ) ≤ Lf (-(11 / 200) : ℝ) (0 : ℝ) := by
  rw [Lf_eq_zero (a := (-(11 / 200) : ℝ)) (Q := (121 / 40000 : ℝ)) (by norm_num)]
  linarith [vl10]

theorem vl11 : Real.log (3721 / 2500 : ℝ) ≤ (397701717491 / 1000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (3721 / 2500 : ℝ)) (z := (1221 / 6221 : ℝ)) (U := (397701717491 / 1000000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem vf11 : Lf (61 / 50 : ℝ) (0 : ℝ) ≤ (0 : ℝ) * π + (-(97740195233049 / 100000000000000) : ℝ) := by
  rw [Lf_eq_zero (a := (61 / 50 : ℝ)) (Q := (3721 / 2500 : ℝ)) (by norm_num)]
  linarith [vl11]

theorem vl12 : Real.log (4 / 625 : ℝ) ≤ (-(5051457286523 / 1000000000000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (4 / 625 : ℝ)) (z := (399 / 1649 : ℝ)) (U := (-5051457286523 / 1000000000000 : ℝ)) 8 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem vf12 : (0 : ℝ) * π + (7051457286523 / 25000000000000 : ℝ) ≤ Lf (-(2 / 25) : ℝ) (0 : ℝ) := by
  rw [Lf_eq_zero (a := (-(2 / 25) : ℝ)) (Q := (4 / 625 : ℝ)) (by norm_num)]
  linarith [vl12]

theorem vl13 : (135317296947 / 1000000000000 : ℝ) ≤ Real.log (11449 / 10000 : ℝ) := by
  have h := (le_log_of_mul_le (q := (11449 / 10000 : ℝ)) (z := (1449 / 21449 : ℝ)) (L := (135317296947 / 1000000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  linarith

theorem vf13 : (0 : ℝ) * π + (-(199521049226671 / 200000000000000) : ℝ) ≤ Lf (107 / 100 : ℝ) (0 : ℝ) := by
  rw [Lf_eq_zero (a := (107 / 100 : ℝ)) (Q := (11449 / 10000 : ℝ)) (by norm_num)]
  linarith [vl13]

theorem vl14 : Real.log (49 / 10000 : ℝ) ≤ (-(1063704014357 / 200000000000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (49 / 10000 : ℝ)) (z := (159 / 1409 : ℝ)) (U := (-1063704014357 / 200000000000 : ℝ)) 8 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem vf14 : Lf (7 / 100 : ℝ) (0 : ℝ) ≤ (0 : ℝ) * π + (-(10245928100499 / 40000000000000) : ℝ) := by
  rw [Lf_eq_zero (a := (7 / 100 : ℝ)) (Q := (49 / 10000 : ℝ)) (by norm_num)]
  linarith [vl14]

/-- `Ψ(0) ≤ -(204867 / 250000)`. -/
theorem psi_at_0 : Psi (0 : ℝ) ≤ (-(204867 / 250000) : ℝ) := by
  unfold Psi
  linarith [vf1, vf2, vf3, vf4, vf5, vf6, vf7, vf8, vf9, vf10, vf11, vf12, vf13, vf14, Real.pi_gt_d20, Real.pi_lt_d20]

theorem va1 : (1 / 2 : ℝ) * π + (-(8076415113 / 200000000000) : ℝ) ≤ Real.arctan (99 / 4 : ℝ) := by
  have h := (arctan_ge_R4 (u := (99 / 4 : ℝ)) (w := (4 / 99 : ℝ)) (U := (8076415113 / 200000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem va2 : (1 / 2 : ℝ) * π + (-(104556084667 / 250000000000) : ℝ) ≤ Real.arctan (9 / 4 : ℝ) := by
  have h := (arctan_ge_R4 (u := (9 / 4 : ℝ)) (w := (4 / 9 : ℝ)) (U := (104556084667 / 250000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem va3 : (1 / 4 : ℝ) * π + (0 : ℝ) ≤ Real.arctan (1 : ℝ) := by
  have h := (arctan_ge_R2 (u := (1 : ℝ)) (w := (0 : ℝ)) (U := (0 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem va4 : (1 / 2 : ℝ) * π + (-(18689412447 / 1000000000000) : ℝ) ≤ Real.arctan (107 / 2 : ℝ) := by
  have h := (arctan_ge_R4 (u := (107 / 2 : ℝ)) (w := (2 / 107 : ℝ)) (U := (18689412447 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem vl15 : Real.log (16657 / 40000 : ℝ) ≤ (-(438024452539 / 500000000000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (16657 / 40000 : ℝ)) (z := (6657 / 26657 : ℝ)) (U := (-438024452539 / 500000000000 : ℝ)) 2 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem va5 : Real.arctan (129 / 4 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(15498909941 / 500000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (129 / 4 : ℝ)) (w := (4 / 129 : ℝ)) (L := (15498909941 / 500000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem vf15 : Lf (129 / 200 : ℝ) (1 / 50 : ℝ) ≤ (1 / 100 : ℝ) * π + (-(185629145657059 / 200000000000000) : ℝ) := by
  rw [Lf_eq_pos (a := (129 / 200 : ℝ)) (y := (1 / 50 : ℝ)) (Q := (16657 / 40000 : ℝ)) (V := (129 / 4 : ℝ)) (by norm_num) (by norm_num)]
  linarith [vl15, va5]

theorem vl16 : (-(702381977439 / 500000000000) : ℝ) ≤ Real.log (9817 / 40000 : ℝ) := by
  have h := (le_log_of_le_mul (q := (9817 / 40000 : ℝ)) (z := (4817 / 14817 : ℝ)) (L := (-702381977439 / 500000000000 : ℝ)) 3 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  linarith

theorem vf16 : (1 / 100 : ℝ) * π + (-(168697344068721 / 200000000000000) : ℝ) ≤ Lf (99 / 200 : ℝ) (1 / 50 : ℝ) := by
  rw [Lf_eq_pos (a := (99 / 200 : ℝ)) (y := (1 / 50 : ℝ)) (Q := (9817 / 40000 : ℝ)) (V := (99 / 4 : ℝ)) (by norm_num) (by norm_num)]
  linarith [vl16, va1]

theorem vl17 : Real.log (47977 / 40000 : ℝ) ≤ (181842275291 / 1000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (47977 / 40000 : ℝ)) (z := (7977 / 87977 : ℝ)) (U := (181842275291 / 1000000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem va6 : Real.arctan (219 / 4 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(2282851189 / 125000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (219 / 4 : ℝ)) (w := (4 / 219 : ℝ)) (L := (2282851189 / 125000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem vf17 : Lf (219 / 200 : ℝ) (1 / 50 : ℝ) ≤ (1 / 100 : ℝ) * π + (-(398322644187367 / 400000000000000) : ℝ) := by
  rw [Lf_eq_pos (a := (219 / 200 : ℝ)) (y := (1 / 50 : ℝ)) (Q := (47977 / 40000 : ℝ)) (V := (219 / 4 : ℝ)) (by norm_num) (by norm_num)]
  linarith [vl17, va6]

theorem vl18 : (-(3010961878377 / 500000000000) : ℝ) ≤ Real.log (97 / 40000 : ℝ) := by
  have h := (le_log_of_le_mul (q := (97 / 40000 : ℝ)) (z := (151 / 1401 : ℝ)) (L := (-3010961878377 / 500000000000 : ℝ)) 9 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  linarith

theorem vf18 : (1 / 100 : ℝ) * π + (-(7554310852013 / 40000000000000) : ℝ) ≤ Lf (9 / 200 : ℝ) (1 / 50 : ℝ) := by
  rw [Lf_eq_pos (a := (9 / 200 : ℝ)) (y := (1 / 50 : ℝ)) (Q := (97 / 40000 : ℝ)) (V := (9 / 4 : ℝ)) (by norm_num) (by norm_num)]
  linarith [vl18, va2]

theorem vl19 : Real.log (3137 / 2500 : ℝ) ≤ (45395239467 / 200000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (3137 / 2500 : ℝ)) (z := (637 / 5637 : ℝ)) (U := (45395239467 / 200000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem va7 : Real.arctan (56 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(17855245139 / 1000000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (56 : ℝ)) (w := (1 / 56 : ℝ)) (L := (17855245139 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem vf19 : Lf (28 / 25 : ℝ) (1 / 50 : ℝ) ≤ (1 / 100 : ℝ) * π + (-(49662521719759 / 50000000000000) : ℝ) := by
  rw [Lf_eq_pos (a := (28 / 25 : ℝ)) (y := (1 / 50 : ℝ)) (Q := (3137 / 2500 : ℝ)) (V := (56 : ℝ)) (by norm_num) (by norm_num)]
  linarith [vl19, va7]

theorem vl20 : (-(7130898834517 / 1000000000000) : ℝ) ≤ Real.log (1 / 1250 : ℝ) := by
  have h := (le_log_of_le_mul (q := (1 / 1250 : ℝ)) (z := (399 / 1649 : ℝ)) (L := (-7130898834517 / 1000000000000 : ℝ)) 11 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  linarith

theorem vf20 : (1 / 200 : ℝ) * π + (-(9130898834517 / 100000000000000) : ℝ) ≤ Lf (1 / 50 : ℝ) (1 / 50 : ℝ) := by
  rw [Lf_eq_pos (a := (1 / 50 : ℝ)) (y := (1 / 50 : ℝ)) (Q := (1 / 1250 : ℝ)) (V := (1 : ℝ)) (by norm_num) (by norm_num)]
  linarith [vl20, va3]

theorem vl21 : Real.log (52457 / 40000 : ℝ) ≤ (135557166131 / 500000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (52457 / 40000 : ℝ)) (z := (12457 / 92457 : ℝ)) (U := (135557166131 / 500000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem va8 : Real.arctan (229 / 4 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(8732736393 / 500000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (229 / 4 : ℝ)) (w := (4 / 229 : ℝ)) (L := (8732736393 / 500000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem vf21 : Lf (229 / 200 : ℝ) (1 / 50 : ℝ) ≤ (1 / 100 : ℝ) * π + (-(39605454169429 / 40000000000000) : ℝ) := by
  rw [Lf_eq_pos (a := (229 / 200 : ℝ)) (y := (1 / 50 : ℝ)) (Q := (52457 / 40000 : ℝ)) (V := (229 / 4 : ℝ)) (by norm_num) (by norm_num)]
  linarith [vl21, va8]

theorem vl22 : Real.log (17 / 40000 : ℝ) ≤ (-(155268427717 / 20000000000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (17 / 40000 : ℝ)) (z := (463 / 1713 : ℝ)) (U := (-155268427717 / 20000000000 : ℝ)) 12 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem va9 : Real.arctan (1 / 4 : ℝ) ≤ (0 : ℝ) * π + (30622332891 / 125000000000 : ℝ) := by
  have h := (arctan_le_R1 (u := (1 / 4 : ℝ)) (U := (30622332891 / 125000000000 : ℝ)) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem vf22 : (0 : ℝ) * π + (3901796040413 / 200000000000000 : ℝ) ≤ Lf (-(1 / 200) : ℝ) (1 / 50 : ℝ) := by
  rw [Lf_eq_neg (a := (-(1 / 200) : ℝ)) (y := (1 / 50 : ℝ)) (Q := (17 / 40000 : ℝ)) (V := (1 / 4 : ℝ)) (by norm_num) (by norm_num)]
  linarith [vl22, va9]

theorem vl23 : Real.log (57137 / 40000 : ℝ) ≤ (178286219343 / 500000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (57137 / 40000 : ℝ)) (z := (17137 / 97137 : ℝ)) (U := (178286219343 / 500000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem va10 : Real.arctan (239 / 4 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(8367419637 / 500000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (239 / 4 : ℝ)) (w := (4 / 239 : ℝ)) (L := (8367419637 / 500000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem vf23 : Lf (239 / 200 : ℝ) (1 / 50 : ℝ) ≤ (1 / 100 : ℝ) * π + (-(196456532934119 / 200000000000000) : ℝ) := by
  rw [Lf_eq_pos (a := (239 / 200 : ℝ)) (y := (1 / 50 : ℝ)) (Q := (57137 / 40000 : ℝ)) (V := (239 / 4 : ℝ)) (by norm_num) (by norm_num)]
  linarith [vl23, va10]

theorem vl24 : Real.log (137 / 40000 : ℝ) ≤ (-(5676653804843 / 1000000000000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (137 / 40000 : ℝ)) (z := (471 / 1721 : ℝ)) (U := (-5676653804843 / 1000000000000 : ℝ)) 9 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem va11 : Real.arctan (11 / 4 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(69754200359 / 200000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (11 / 4 : ℝ)) (w := (4 / 11 : ℝ)) (L := (69754200359 / 200000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem vf24 : (-(1 / 100) : ℝ) * π + (87233359867633 / 400000000000000 : ℝ) ≤ Lf (-(11 / 200) : ℝ) (1 / 50 : ℝ) := by
  rw [Lf_eq_neg (a := (-(11 / 200) : ℝ)) (y := (1 / 50 : ℝ)) (Q := (137 / 40000 : ℝ)) (V := (11 / 4 : ℝ)) (by norm_num) (by norm_num)]
  linarith [vl24, va11]

theorem vl25 : Real.log (1861 / 1250 : ℝ) ≤ (397970426347 / 1000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (1861 / 1250 : ℝ)) (z := (611 / 3111 : ℝ)) (U := (397970426347 / 1000000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem va12 : Real.arctan (61 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(4097993577 / 250000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (61 : ℝ)) (w := (1 / 61 : ℝ)) (L := (4097993577 / 250000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem vf25 : Lf (61 / 50 : ℝ) (1 / 50 : ℝ) ≤ (1 / 100 : ℝ) * π + (-(97756587941449 / 100000000000000) : ℝ) := by
  rw [Lf_eq_pos (a := (61 / 50 : ℝ)) (y := (1 / 50 : ℝ)) (Q := (1861 / 1250 : ℝ)) (V := (61 : ℝ)) (by norm_num) (by norm_num)]
  linarith [vl25, va12]

theorem vl26 : Real.log (17 / 2500 : ℝ) ≤ (-(99816653293 / 20000000000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (17 / 2500 : ℝ)) (z := (463 / 1713 : ℝ)) (U := (-99816653293 / 20000000000 : ℝ)) 8 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem va13 : Real.arctan (4 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(244978663123 / 1000000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (4 : ℝ)) (w := (1 / 4 : ℝ)) (L := (244978663123 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem vf26 : (-(1 / 100) : ℝ) * π + (14226643992423 / 50000000000000 : ℝ) ≤ Lf (-(2 / 25) : ℝ) (1 / 50 : ℝ) := by
  rw [Lf_eq_neg (a := (-(2 / 25) : ℝ)) (y := (1 / 50 : ℝ)) (Q := (17 / 2500 : ℝ)) (V := (4 : ℝ)) (by norm_num) (by norm_num)]
  linarith [vl26, va13]

theorem vl27 : (135666611421 / 1000000000000 : ℝ) ≤ Real.log (11453 / 10000 : ℝ) := by
  have h := (le_log_of_mul_le (q := (11453 / 10000 : ℝ)) (z := (1453 / 21453 : ℝ)) (L := (135666611421 / 1000000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  linarith

theorem vf27 : (1 / 100 : ℝ) * π + (-(199558430227741 / 200000000000000) : ℝ) ≤ Lf (107 / 100 : ℝ) (1 / 50 : ℝ) := by
  rw [Lf_eq_pos (a := (107 / 100 : ℝ)) (y := (1 / 50 : ℝ)) (Q := (11453 / 10000 : ℝ)) (V := (107 / 2 : ℝ)) (by norm_num) (by norm_num)]
  linarith [vl27, va4]

theorem vl28 : Real.log (53 / 10000 : ℝ) ≤ (-(655006057043 / 125000000000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (53 / 10000 : ℝ)) (z := (223 / 1473 : ℝ)) (U := (-655006057043 / 125000000000 : ℝ)) 8 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem va14 : Real.arctan (7 / 2 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(139149829487 / 500000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (7 / 2 : ℝ)) (w := (2 / 7 : ℝ)) (L := (139149829487 / 500000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem vf28 : Lf (7 / 100 : ℝ) (1 / 50 : ℝ) ≤ (1 / 100 : ℝ) * π + (-(1618548057197 / 6250000000000) : ℝ) := by
  rw [Lf_eq_pos (a := (7 / 100 : ℝ)) (y := (1 / 50 : ℝ)) (Q := (53 / 10000 : ℝ)) (V := (7 / 2 : ℝ)) (by norm_num) (by norm_num)]
  linarith [vl28, va14]

/-- `Ψ(1 / 50) ≤ -(196397 / 250000)`. -/
theorem psi_at_1 : Psi (1 / 50 : ℝ) ≤ (-(196397 / 250000) : ℝ) := by
  unfold Psi
  linarith [vf15, vf16, vf17, vf18, vf19, vf20, vf21, vf22, vf23, vf24, vf25, vf26, vf27, vf28, Real.pi_gt_d20, Real.pi_lt_d20]

theorem va15 : (1 / 2 : ℝ) * π + (-(50334326079 / 500000000000) : ℝ) ≤ Real.arctan (99 / 10 : ℝ) := by
  have h := (arctan_ge_R4 (u := (99 / 10 : ℝ)) (w := (10 / 99 : ℝ)) (U := (50334326079 / 500000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem va16 : (1 / 4 : ℝ) * π + (-(52583061611 / 1000000000000) : ℝ) ≤ Real.arctan (9 / 10 : ℝ) := by
  have h := (arctan_ge_R2 (u := (9 / 10 : ℝ)) (w := (1 / 19 : ℝ)) (U := (52583061611 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem va17 : (0 : ℝ) * π + (38050636827 / 100000000000 : ℝ) ≤ Real.arctan (2 / 5 : ℝ) := by
  have h := (arctan_ge_R1 (u := (2 / 5 : ℝ)) (L := (38050636827 / 100000000000 : ℝ)) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem va18 : (1 / 2 : ℝ) * π + (-(11673751011 / 250000000000) : ℝ) ≤ Real.arctan (107 / 5 : ℝ) := by
  have h := (arctan_ge_R4 (u := (107 / 5 : ℝ)) (w := (5 / 107 : ℝ)) (U := (11673751011 / 250000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem vl29 : Real.log (16741 / 40000 : ℝ) ≤ (-(54438665821 / 62500000000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (16741 / 40000 : ℝ)) (z := (6741 / 26741 : ℝ)) (U := (-54438665821 / 62500000000 : ℝ)) 2 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem va19 : Real.arctan (129 / 10 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(77364659427 / 1000000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (129 / 10 : ℝ)) (w := (10 / 129 : ℝ)) (L := (77364659427 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem vf29 : Lf (129 / 200 : ℝ) (1 / 20 : ℝ) ≤ (1 / 40 : ℝ) * π + (-(92977174860771 / 100000000000000) : ℝ) := by
  rw [Lf_eq_pos (a := (129 / 200 : ℝ)) (y := (1 / 20 : ℝ)) (Q := (16741 / 40000 : ℝ)) (V := (129 / 10 : ℝ)) (by norm_num) (by norm_num)]
  linarith [vl29, va19]

theorem vl30 : (-(698121891097 / 500000000000) : ℝ) ≤ Real.log (9901 / 40000 : ℝ) := by
  have h := (le_log_of_le_mul (q := (9901 / 40000 : ℝ)) (z := (4901 / 14901 : ℝ)) (L := (-698121891097 / 500000000000 : ℝ)) 3 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  linarith

theorem vf30 : (1 / 40 : ℝ) * π + (-(169120753740183 / 200000000000000) : ℝ) ≤ Lf (99 / 200 : ℝ) (1 / 20 : ℝ) := by
  rw [Lf_eq_pos (a := (99 / 200 : ℝ)) (y := (1 / 20 : ℝ)) (Q := (9901 / 40000 : ℝ)) (V := (99 / 10 : ℝ)) (by norm_num) (by norm_num)]
  linarith [vl30, va15]

theorem vl31 : Real.log (48061 / 40000 : ℝ) ≤ (183591583303 / 1000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (48061 / 40000 : ℝ)) (z := (8061 / 88061 : ℝ)) (U := (183591583303 / 1000000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem va20 : Real.arctan (219 / 10 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(22815202261 / 500000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (219 / 10 : ℝ)) (w := (10 / 219 : ℝ)) (L := (22815202261 / 500000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem vf31 : Lf (219 / 200 : ℝ) (1 / 20 : ℝ) ≤ (1 / 40 : ℝ) * π + (-(398706051347083 / 400000000000000) : ℝ) := by
  rw [Lf_eq_pos (a := (219 / 200 : ℝ)) (y := (1 / 20 : ℝ)) (Q := (48061 / 40000 : ℝ)) (V := (219 / 10 : ℝ)) (by norm_num) (by norm_num)]
  linarith [vl31, va20]

theorem vl32 : (-(5398137703751 / 1000000000000) : ℝ) ≤ Real.log (181 / 40000 : ℝ) := by
  have h := (le_log_of_le_mul (q := (181 / 40000 : ℝ)) (z := (99 / 1349 : ℝ)) (L := (-5398137703751 / 1000000000000 : ℝ)) 8 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  linarith

theorem vf32 : (1 / 80 : ℝ) * π + (-(67634900565979 / 400000000000000) : ℝ) ≤ Lf (9 / 200 : ℝ) (1 / 20 : ℝ) := by
  rw [Lf_eq_pos (a := (9 / 200 : ℝ)) (y := (1 / 20 : ℝ)) (Q := (181 / 40000 : ℝ)) (V := (9 / 10 : ℝ)) (by norm_num) (by norm_num)]
  linarith [vl32, va16]

theorem vl33 : Real.log (12569 / 10000 : ℝ) ≤ (228648371949 / 1000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (12569 / 10000 : ℝ)) (z := (2569 / 22569 : ℝ)) (U := (228648371949 / 1000000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem va21 : Real.arctan (112 / 5 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(22306617523 / 500000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (112 / 5 : ℝ)) (w := (5 / 112 : ℝ)) (L := (22306617523 / 500000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem vf33 : Lf (28 / 25 : ℝ) (1 / 20 : ℝ) ≤ (1 / 40 : ℝ) * π + (-(49709378673043 / 50000000000000) : ℝ) := by
  rw [Lf_eq_pos (a := (28 / 25 : ℝ)) (y := (1 / 20 : ℝ)) (Q := (12569 / 10000 : ℝ)) (V := (112 / 5 : ℝ)) (by norm_num) (by norm_num)]
  linarith [vl33, va21]

theorem vl34 : (-(1168608908849 / 200000000000) : ℝ) ≤ Real.log (29 / 10000 : ℝ) := by
  have h := (le_log_of_le_mul (q := (29 / 10000 : ℝ)) (z := (303 / 1553 : ℝ)) (L := (-1168608908849 / 200000000000 : ℝ)) 9 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  linarith

theorem vf34 : (0 : ℝ) * π + (-(1188102540579 / 20000000000000) : ℝ) ≤ Lf (1 / 50 : ℝ) (1 / 20 : ℝ) := by
  rw [Lf_eq_pos (a := (1 / 50 : ℝ)) (y := (1 / 20 : ℝ)) (Q := (29 / 10000 : ℝ)) (V := (2 / 5 : ℝ)) (by norm_num) (by norm_num)]
  linarith [vl34, va17]

theorem vl35 : Real.log (52541 / 40000 : ℝ) ≤ (6817859077 / 25000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (52541 / 40000 : ℝ)) (z := (12541 / 92541 : ℝ)) (U := (6817859077 / 25000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem va22 : Real.arctan (229 / 10 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(43640397 / 1000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (229 / 10 : ℝ)) (w := (10 / 229 : ℝ)) (L := (43640397 / 1000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem vf35 : Lf (229 / 200 : ℝ) (1 / 20 : ℝ) ≤ (1 / 40 : ℝ) * π + (-(9910530469867 / 10000000000000) : ℝ) := by
  rw [Lf_eq_pos (a := (229 / 200 : ℝ)) (y := (1 / 20 : ℝ)) (Q := (52541 / 40000 : ℝ)) (V := (229 / 10 : ℝ)) (by norm_num) (by norm_num)]
  linarith [vl35, va22]

theorem vl36 : Real.log (101 / 40000 : ℝ) ≤ (-(1196302842783 / 200000000000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (101 / 40000 : ℝ)) (z := (183 / 1433 : ℝ)) (U := (-1196302842783 / 200000000000 : ℝ)) 9 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem va23 : Real.arctan (1 / 10 : ℝ) ≤ (0 : ℝ) * π + (24917163123 / 250000000000 : ℝ) := by
  have h := (arctan_le_R1 (u := (1 / 10 : ℝ)) (U := (24917163123 / 250000000000 : ℝ)) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem vf36 : (0 : ℝ) * π + (239525646563 / 16000000000000 : ℝ) ≤ Lf (-(1 / 200) : ℝ) (1 / 20 : ℝ) := by
  rw [Lf_eq_neg (a := (-(1 / 200) : ℝ)) (y := (1 / 20 : ℝ)) (Q := (101 / 40000 : ℝ)) (V := (1 / 10 : ℝ)) (by norm_num) (by norm_num)]
  linarith [vl36, va23]

theorem vl37 : Real.log (57221 / 40000 : ℝ) ≤ (358041509763 / 1000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (57221 / 40000 : ℝ)) (z := (17221 / 97221 : ℝ)) (U := (358041509763 / 1000000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem va24 : Real.arctan (239 / 10 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(41816613207 / 1000000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (239 / 10 : ℝ)) (w := (10 / 239 : ℝ)) (L := (41816613207 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem vf37 : Lf (239 / 200 : ℝ) (1 / 20 : ℝ) ≤ (1 / 40 : ℝ) * π + (-(393264411430783 / 400000000000000) : ℝ) := by
  rw [Lf_eq_pos (a := (239 / 200 : ℝ)) (y := (1 / 20 : ℝ)) (Q := (57221 / 40000 : ℝ)) (V := (239 / 10 : ℝ)) (by norm_num) (by norm_num)]
  linarith [vl37, va24]

theorem vl38 : Real.log (221 / 40000 : ℝ) ≤ (-(2599236014749 / 500000000000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (221 / 40000 : ℝ)) (z := (259 / 1509 : ℝ)) (U := (-2599236014749 / 500000000000 : ℝ)) 8 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem va25 : Real.arctan (11 / 10 : ℝ) ≤ (1 / 4 : ℝ) * π + (47583103277 / 1000000000000 : ℝ) := by
  have h := (arctan_le_R3 (u := (11 / 10 : ℝ)) (w := (1 / 21 : ℝ)) (U := (47583103277 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem vf38 : (-(1 / 80) : ℝ) * π + (39115765129469 / 200000000000000 : ℝ) ≤ Lf (-(11 / 200) : ℝ) (1 / 20 : ℝ) := by
  rw [Lf_eq_neg (a := (-(11 / 200) : ℝ)) (y := (1 / 20 : ℝ)) (Q := (221 / 40000 : ℝ)) (V := (11 / 10 : ℝ)) (by norm_num) (by norm_num)]
  linarith [vl38, va25]

theorem vl39 : Real.log (14909 / 10000 : ℝ) ≤ (399379964453 / 1000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (14909 / 10000 : ℝ)) (z := (4909 / 24909 : ℝ)) (U := (399379964453 / 1000000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem va26 : Real.arctan (122 / 5 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(20480341767 / 500000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (122 / 5 : ℝ)) (w := (5 / 122 : ℝ)) (L := (20480341767 / 500000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem vf39 : Lf (61 / 50 : ℝ) (1 / 20 : ℝ) ≤ (1 / 40 : ℝ) * π + (-(97842625586037 / 100000000000000) : ℝ) := by
  rw [Lf_eq_pos (a := (61 / 50 : ℝ)) (y := (1 / 20 : ℝ)) (Q := (14909 / 10000 : ℝ)) (V := (122 / 5 : ℝ)) (by norm_num) (by norm_num)]
  linarith [vl39, va26]

theorem vl40 : Real.log (89 / 10000 : ℝ) ≤ (-(590213000053 / 125000000000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (89 / 10000 : ℝ)) (z := (87 / 1337 : ℝ)) (U := (-590213000053 / 125000000000 : ℝ)) 7 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem va27 : Real.arctan (8 / 5 : ℝ) ≤ (1 / 4 : ℝ) * π + (113399424027 / 500000000000 : ℝ) := by
  have h := (arctan_le_R3 (u := (8 / 5 : ℝ)) (w := (3 / 13 : ℝ)) (U := (113399424027 / 500000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem vf40 : (-(1 / 80) : ℝ) * π + (12876410880713 / 50000000000000 : ℝ) ≤ Lf (-(2 / 25) : ℝ) (1 / 20 : ℝ) := by
  rw [Lf_eq_neg (a := (-(2 / 25) : ℝ)) (y := (1 / 20 : ℝ)) (Q := (89 / 10000 : ℝ)) (V := (8 / 5 : ℝ)) (by norm_num) (by norm_num)]
  linarith [vl40, va27]

theorem vl41 : (27499702637 / 200000000000 : ℝ) ≤ Real.log (5737 / 5000 : ℝ) := by
  have h := (le_log_of_mul_le (q := (5737 / 5000 : ℝ)) (z := (737 / 10737 : ℝ)) (L := (27499702637 / 200000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  linarith

theorem vf41 : (1 / 40 : ℝ) * π + (-(39950921825929 / 40000000000000) : ℝ) ≤ Lf (107 / 100 : ℝ) (1 / 20 : ℝ) := by
  rw [Lf_eq_pos (a := (107 / 100 : ℝ)) (y := (1 / 20 : ℝ)) (Q := (5737 / 5000 : ℝ)) (V := (107 / 5 : ℝ)) (by norm_num) (by norm_num)]
  linarith [vl41, va18]

theorem vl42 : Real.log (37 / 5000 : ℝ) ≤ (-(981255055229 / 200000000000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (37 / 5000 : ℝ)) (z := (559 / 1809 : ℝ)) (U := (-981255055229 / 200000000000 : ℝ)) 8 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem va28 : Real.arctan (7 / 5 : ℝ) ≤ (1 / 4 : ℝ) * π + (33029735483 / 200000000000 : ℝ) := by
  have h := (arctan_le_R3 (u := (7 / 5 : ℝ)) (w := (1 / 6 : ℝ)) (U := (33029735483 / 200000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem vf42 : Lf (7 / 100 : ℝ) (1 / 20 : ℝ) ≤ (1 / 80 : ℝ) * π + (-(9338488031773 / 40000000000000) : ℝ) := by
  rw [Lf_eq_pos (a := (7 / 100 : ℝ)) (y := (1 / 20 : ℝ)) (Q := (37 / 5000 : ℝ)) (V := (7 / 5 : ℝ)) (by norm_num) (by norm_num)]
  linarith [vl42, va28]

/-- `Ψ(1 / 20) ≤ -(79329 / 100000)`. -/
theorem psi_at_2 : Psi (1 / 20 : ℝ) ≤ (-(79329 / 100000) : ℝ) := by
  unfold Psi
  linarith [vf29, vf30, vf31, vf32, vf33, vf34, vf35, vf36, vf37, vf38, vf39, vf40, vf41, vf42, Real.pi_gt_d20, Real.pi_lt_d20]

theorem va29 : (1 / 2 : ℝ) * π + (-(87192750949 / 250000000000) : ℝ) ≤ Real.arctan (11 / 4 : ℝ) := by
  have h := (arctan_ge_R4 (u := (11 / 4 : ℝ)) (w := (4 / 11 : ℝ)) (U := (87192750949 / 250000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem va30 : (0 : ℝ) * π + (244978663123 / 1000000000000 : ℝ) ≤ Real.arctan (1 / 4 : ℝ) := by
  have h := (arctan_ge_R1 (u := (1 / 4 : ℝ)) (L := (244978663123 / 1000000000000 : ℝ)) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem va31 : (0 : ℝ) * π + (110657221173 / 1000000000000 : ℝ) ≤ Real.arctan (1 / 9 : ℝ) := by
  have h := (arctan_ge_R1 (u := (1 / 9 : ℝ)) (L := (110657221173 / 1000000000000 : ℝ)) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem va32 : (1 / 2 : ℝ) * π + (-(166663827771 / 1000000000000) : ℝ) ≤ Real.arctan (107 / 18 : ℝ) := by
  have h := (arctan_ge_R4 (u := (107 / 18 : ℝ)) (w := (18 / 107 : ℝ)) (U := (166663827771 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem vl43 : Real.log (17937 / 40000 : ℝ) ≤ (-(200503458719 / 250000000000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (17937 / 40000 : ℝ)) (z := (7937 / 27937 : ℝ)) (U := (-200503458719 / 250000000000 : ℝ)) 2 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem va33 : Real.arctan (43 / 12 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(27214589051 / 100000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (43 / 12 : ℝ)) (w := (12 / 43 : ℝ)) (L := (27214589051 / 100000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem vf43 : Lf (129 / 200 : ℝ) (9 / 50 : ℝ) ≤ (9 / 100 : ℝ) * π + (-(95263572203931 / 100000000000000) : ℝ) := by
  rw [Lf_eq_pos (a := (129 / 200 : ℝ)) (y := (9 / 50 : ℝ)) (Q := (17937 / 40000 : ℝ)) (V := (43 / 12 : ℝ)) (by norm_num) (by norm_num)]
  linarith [vl43, va33]

theorem vl44 : (-(320551163269 / 250000000000) : ℝ) ≤ Real.log (11097 / 40000 : ℝ) := by
  have h := (le_log_of_le_mul (q := (11097 / 40000 : ℝ)) (z := (1097 / 21097 : ℝ)) (L := (-320551163269 / 250000000000 : ℝ)) 2 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  linarith

theorem vf44 : (9 / 100 : ℝ) * π + (-(87512443231959 / 100000000000000) : ℝ) ≤ Lf (99 / 200 : ℝ) (9 / 50 : ℝ) := by
  rw [Lf_eq_pos (a := (99 / 200 : ℝ)) (y := (9 / 50 : ℝ)) (Q := (11097 / 40000 : ℝ)) (V := (11 / 4 : ℝ)) (by norm_num) (by norm_num)]
  linarith [vl44, va29]

theorem vl45 : Real.log (49257 / 40000 : ℝ) ≤ (41634407077 / 200000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (49257 / 40000 : ℝ)) (z := (9257 / 89257 : ℝ)) (U := (41634407077 / 200000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem va34 : Real.arctan (73 / 12 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(3258529177 / 20000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (73 / 12 : ℝ)) (w := (12 / 73 : ℝ)) (L := (3258529177 / 20000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem vf45 : Lf (219 / 200 : ℝ) (9 / 50 : ℝ) ≤ (9 / 100 : ℝ) * π + (-(80828205857577 / 80000000000000) : ℝ) := by
  rw [Lf_eq_pos (a := (219 / 200 : ℝ)) (y := (9 / 50 : ℝ)) (Q := (49257 / 40000 : ℝ)) (V := (73 / 12 : ℝ)) (by norm_num) (by norm_num)]
  linarith [vl45, va34]

theorem vl46 : (-(210560764723 / 62500000000) : ℝ) ≤ Real.log (1377 / 40000 : ℝ) := by
  have h := (le_log_of_le_mul (q := (1377 / 40000 : ℝ)) (z := (127 / 2627 : ℝ)) (L := (-210560764723 / 62500000000 : ℝ)) 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  linarith

theorem vf46 : (0 : ℝ) * π + (-(3835285796907 / 50000000000000) : ℝ) ≤ Lf (9 / 200 : ℝ) (9 / 50 : ℝ) := by
  rw [Lf_eq_pos (a := (9 / 200 : ℝ)) (y := (9 / 50 : ℝ)) (Q := (1377 / 40000 : ℝ)) (V := (1 / 4 : ℝ)) (by norm_num) (by norm_num)]
  linarith [vl46, va30]

theorem vl47 : Real.log (3217 / 2500 : ℝ) ≤ (252158516383 / 1000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (3217 / 2500 : ℝ)) (z := (717 / 5717 : ℝ)) (U := (252158516383 / 1000000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem va35 : Real.arctan (56 / 9 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(159351640903 / 1000000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (56 / 9 : ℝ)) (w := (9 / 56 : ℝ)) (L := (159351640903 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem vf47 : Lf (28 / 25 : ℝ) (9 / 50 : ℝ) ≤ (9 / 100 : ℝ) * π + (-(50373726309403 / 50000000000000) : ℝ) := by
  rw [Lf_eq_pos (a := (28 / 25 : ℝ)) (y := (9 / 50 : ℝ)) (Q := (3217 / 2500 : ℝ)) (V := (56 / 9 : ℝ)) (by norm_num) (by norm_num)]
  linarith [vl47, va35]

theorem vl48 : (-(3417326764793 / 1000000000000) : ℝ) ≤ Real.log (41 / 1250 : ℝ) := by
  have h := (le_log_of_le_mul (q := (41 / 1250 : ℝ)) (z := (31 / 1281 : ℝ)) (L := (-3417326764793 / 1000000000000 : ℝ)) 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  linarith

theorem vf48 : (0 : ℝ) * π + (-(3425496783679 / 100000000000000) : ℝ) ≤ Lf (1 / 50 : ℝ) (9 / 50 : ℝ) := by
  rw [Lf_eq_pos (a := (1 / 50 : ℝ)) (y := (9 / 50 : ℝ)) (Q := (41 / 1250 : ℝ)) (V := (1 / 9 : ℝ)) (by norm_num) (by norm_num)]
  linarith [vl48, va31]

theorem vl49 : Real.log (53737 / 40000 : ℝ) ≤ (36902790397 / 125000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (53737 / 40000 : ℝ)) (z := (13737 / 93737 : ℝ)) (U := (36902790397 / 125000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem va36 : Real.arctan (229 / 36 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(38982270123 / 250000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (229 / 36 : ℝ)) (w := (36 / 229 : ℝ)) (L := (38982270123 / 250000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem vf49 : Lf (229 / 200 : ℝ) (9 / 50 : ℝ) ≤ (9 / 100 : ℝ) * π + (-(10040524544703 / 10000000000000) : ℝ) := by
  rw [Lf_eq_pos (a := (229 / 200 : ℝ)) (y := (9 / 50 : ℝ)) (Q := (53737 / 40000 : ℝ)) (V := (229 / 36 : ℝ)) (by norm_num) (by norm_num)]
  linarith [vl49, va36]

theorem vl50 : Real.log (1297 / 40000 : ℝ) ≤ (-(3428825547479 / 1000000000000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (1297 / 40000 : ℝ)) (z := (47 / 2547 : ℝ)) (U := (-3428825547479 / 1000000000000 : ℝ)) 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem va37 : Real.arctan (1 / 36 : ℝ) ≤ (0 : ℝ) * π + (13885318297 / 500000000000 : ℝ) := by
  have h := (arctan_le_R1 (u := (1 / 36 : ℝ)) (U := (13885318297 / 500000000000 : ℝ)) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem vf50 : (0 : ℝ) * π + (3429339712711 / 400000000000000 : ℝ) ≤ Lf (-(1 / 200) : ℝ) (9 / 50 : ℝ) := by
  rw [Lf_eq_neg (a := (-(1 / 200) : ℝ)) (y := (9 / 50 : ℝ)) (Q := (1297 / 40000 : ℝ)) (V := (1 / 36 : ℝ)) (by norm_num) (by norm_num)]
  linarith [vl50, va37]

theorem vl51 : Real.log (58417 / 40000 : ℝ) ≤ (378727489251 / 1000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (58417 / 40000 : ℝ)) (z := (18417 / 98417 : ℝ)) (U := (378727489251 / 1000000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem va38 : Real.arctan (239 / 36 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(74751847743 / 500000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (239 / 36 : ℝ)) (w := (36 / 239 : ℝ)) (L := (74751847743 / 500000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem vf51 : Lf (239 / 200 : ℝ) (9 / 50 : ℝ) ≤ (9 / 100 : ℝ) * π + (-(398248396144003 / 400000000000000) : ℝ) := by
  rw [Lf_eq_pos (a := (239 / 200 : ℝ)) (y := (9 / 50 : ℝ)) (Q := (58417 / 40000 : ℝ)) (V := (239 / 36 : ℝ)) (by norm_num) (by norm_num)]
  linarith [vl51, va38]

theorem vl52 : Real.log (1417 / 40000 : ℝ) ≤ (-(668067498421 / 200000000000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (1417 / 40000 : ℝ)) (z := (167 / 2667 : ℝ)) (U := (-668067498421 / 200000000000 : ℝ)) 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem va39 : Real.arctan (11 / 36 : ℝ) ≤ (0 : ℝ) * π + (148272904539 / 500000000000 : ℝ) := by
  have h := (arctan_le_R1 (u := (11 / 36 : ℝ)) (U := (148272904539 / 500000000000 : ℝ)) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem vf52 : (0 : ℝ) * π + (37392414159539 / 400000000000000 : ℝ) ≤ Lf (-(11 / 200) : ℝ) (9 / 50 : ℝ) := by
  rw [Lf_eq_neg (a := (-(11 / 200) : ℝ)) (y := (9 / 50 : ℝ)) (Q := (1417 / 40000 : ℝ)) (V := (11 / 36 : ℝ)) (by norm_num) (by norm_num)]
  linarith [vl52, va39]

theorem vl53 : Real.log (1901 / 1250 : ℝ) ≤ (209618256097 / 500000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (1901 / 1250 : ℝ)) (z := (651 / 3151 : ℝ)) (U := (209618256097 / 500000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem va40 : Real.arctan (61 / 9 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(146484178393 / 1000000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (61 / 9 : ℝ)) (w := (9 / 61 : ℝ)) (L := (146484178393 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem vf53 : Lf (61 / 50 : ℝ) (9 / 50 : ℝ) ≤ (9 / 100 : ℝ) * π + (-(2476582199181 / 2500000000000) : ℝ) := by
  rw [Lf_eq_pos (a := (61 / 50 : ℝ)) (y := (9 / 50 : ℝ)) (Q := (1901 / 1250 : ℝ)) (V := (61 / 9 : ℝ)) (by norm_num) (by norm_num)]
  linarith [vl53, va40]

theorem vl54 : Real.log (97 / 2500 : ℝ) ≤ (-(3249335031053 / 1000000000000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (97 / 2500 : ℝ)) (z := (151 / 1401 : ℝ)) (U := (-3249335031053 / 1000000000000 : ℝ)) 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem va41 : Real.arctan (4 / 9 : ℝ) ≤ (0 : ℝ) * π + (104556084667 / 250000000000 : ℝ) := by
  have h := (arctan_le_R1 (u := (4 / 9 : ℝ)) (U := (104556084667 / 250000000000 : ℝ)) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem vf54 : (0 : ℝ) * π + (3367325507047 / 25000000000000 : ℝ) ≤ Lf (-(2 / 25) : ℝ) (9 / 50 : ℝ) := by
  rw [Lf_eq_neg (a := (-(2 / 25) : ℝ)) (y := (9 / 50 : ℝ)) (Q := (97 / 2500 : ℝ)) (V := (4 / 9 : ℝ)) (by norm_num) (by norm_num)]
  linarith [vl54, va41]

theorem vl55 : (81611840551 / 500000000000 : ℝ) ≤ Real.log (11773 / 10000 : ℝ) := by
  have h := (le_log_of_mul_le (q := (11773 / 10000 : ℝ)) (z := (1773 / 21773 : ℝ)) (L := (81611840551 / 500000000000 : ℝ)) 0 (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  linarith

theorem vf55 : (9 / 100 : ℝ) * π + (-(101267481960921 / 100000000000000) : ℝ) ≤ Lf (107 / 100 : ℝ) (9 / 50 : ℝ) := by
  rw [Lf_eq_pos (a := (107 / 100 : ℝ)) (y := (9 / 50 : ℝ)) (Q := (11773 / 10000 : ℝ)) (V := (107 / 18 : ℝ)) (by norm_num) (by norm_num)]
  linarith [vl55, va32]

theorem vl56 : Real.log (373 / 10000 : ℝ) ≤ (-(411095243879 / 125000000000) : ℝ) := by
  have h := (log_le_of_mul_le (q := (373 / 10000 : ℝ)) (z := (121 / 1371 : ℝ)) (U := (-411095243879 / 125000000000 : ℝ)) 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem va42 : Real.arctan (7 / 18 : ℝ) ≤ (0 : ℝ) * π + (185445644779 / 500000000000 : ℝ) := by
  have h := (arctan_le_R1 (u := (7 / 18 : ℝ)) (U := (185445644779 / 500000000000 : ℝ)) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem vf56 : Lf (7 / 100 : ℝ) (9 / 50 : ℝ) ≤ (0 : ℝ) * π + (-(1479327952071 / 12500000000000) : ℝ) := by
  rw [Lf_eq_pos (a := (7 / 100 : ℝ)) (y := (9 / 50 : ℝ)) (Q := (373 / 10000 : ℝ)) (V := (7 / 18 : ℝ)) (by norm_num) (by norm_num)]
  linarith [vl56, va42]

/-- `Ψ(9 / 50) ≤ -(157397 / 125000)`. -/
theorem psi_at_3 : Psi (9 / 50 : ℝ) ≤ (-(157397 / 125000) : ℝ) := by
  unfold Psi
  linarith [vf43, vf44, vf45, vf46, vf47, vf48, vf49, vf50, vf51, vf52, vf53, vf54, vf55, vf56, Real.pi_gt_d20, Real.pi_lt_d20]

theorem va43 : (0 : ℝ) * π + (91927860807 / 200000000000 : ℝ) ≤ Real.arctan (99 / 200 : ℝ) := by
  have h := (arctan_ge_R1 (u := (99 / 200 : ℝ)) (L := (91927860807 / 200000000000 : ℝ)) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem va44 : (0 : ℝ) * π + (11242415463 / 250000000000 : ℝ) ≤ Real.arctan (9 / 200 : ℝ) := by
  have h := (arctan_ge_R1 (u := (9 / 200 : ℝ)) (L := (11242415463 / 250000000000 : ℝ)) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem va45 : (0 : ℝ) * π + (19997333973 / 1000000000000 : ℝ) ≤ Real.arctan (1 / 50 : ℝ) := by
  have h := (arctan_ge_R1 (u := (1 / 50 : ℝ)) (L := (19997333973 / 1000000000000 : ℝ)) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem va46 : (1 / 4 : ℝ) * π + (33803543693 / 1000000000000 : ℝ) ≤ Real.arctan (107 / 100 : ℝ) := by
  have h := (arctan_ge_R3 (u := (107 / 100 : ℝ)) (w := (7 / 207 : ℝ)) (L := (33803543693 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

/-! ## The cells -/

/-- Cell `[0, 1 / 50]`: `Ψ(l) ≤ -(204867 / 250000)`, `Ψ' ≤ 2248867 / 500000`, bound `-0.729513`. -/
theorem vert_cell_1 : ∀ η, (0 : ℝ) ≤ η → η ≤ (1 / 50 : ℝ) → Psi η ≤ -18 / 25 := by
  have hM : ∀ ζ, (0 : ℝ) < ζ → ζ < (1 / 50 : ℝ) → dPsi ζ ≤ (2248867 / 500000 : ℝ) := by
    intro ζ h1 h2
    have hζ : 0 < ζ := by linarith
    have := Real.arctan_lt_pi_div_two (129 / 200 / ζ)
    have : Real.arctan (99 / 4 : ℝ) ≤ Real.arctan (99 / 200 / ζ) := arctan_div_ge_of_nonneg (by norm_num) hζ h2.le (by norm_num)
    have := Real.arctan_lt_pi_div_two (219 / 200 / ζ)
    have : Real.arctan (9 / 4 : ℝ) ≤ Real.arctan (9 / 200 / ζ) := arctan_div_ge_of_nonneg (by norm_num) hζ h2.le (by norm_num)
    have := Real.arctan_lt_pi_div_two (28 / 25 / ζ)
    have : Real.arctan (1 : ℝ) ≤ Real.arctan (1 / 50 / ζ) := arctan_div_ge_of_nonneg (by norm_num) hζ h2.le (by norm_num)
    have := Real.arctan_lt_pi_div_two (229 / 200 / ζ)
    have := Real.neg_pi_div_two_lt_arctan (-(1 / 200) / ζ)
    have := Real.arctan_lt_pi_div_two (239 / 200 / ζ)
    have := Real.neg_pi_div_two_lt_arctan (-(11 / 200) / ζ)
    have := Real.arctan_lt_pi_div_two (61 / 50 / ζ)
    have := Real.neg_pi_div_two_lt_arctan (-(2 / 25) / ζ)
    have : Real.arctan (107 / 2 : ℝ) ≤ Real.arctan (107 / 100 / ζ) := arctan_div_ge_of_nonneg (by norm_num) hζ h2.le (by norm_num)
    have := Real.arctan_lt_pi_div_two (7 / 100 / ζ)
    unfold dPsi
    linarith [va1, va2, va3, va4, Real.pi_gt_d20, Real.pi_lt_d20]
  intro η h1 h2
  have h := Psi_le_of_deriv (l := (0 : ℝ)) (r := (1 / 50 : ℝ)) (M := (2248867 / 500000 : ℝ)) (by norm_num) hM (by norm_num) η h1 h2
  have hB := psi_at_0
  linarith

/-- Cell `[1 / 50, 1 / 20]`: `Ψ(l) ≤ -(196397 / 250000)`, `Ψ' ≤ 184363 / 100000`, bound `-0.730279`. -/
theorem vert_cell_2 : ∀ η, (1 / 50 : ℝ) ≤ η → η ≤ (1 / 20 : ℝ) → Psi η ≤ -18 / 25 := by
  have hM : ∀ ζ, (1 / 50 : ℝ) < ζ → ζ < (1 / 20 : ℝ) → dPsi ζ ≤ (184363 / 100000 : ℝ) := by
    intro ζ h1 h2
    have hζ : 0 < ζ := by linarith
    have : Real.arctan (129 / 200 / ζ) ≤ Real.arctan (129 / 4 : ℝ) := arctan_div_le_of_nonneg (by norm_num) (by norm_num) h1.le (by norm_num)
    have : Real.arctan (99 / 10 : ℝ) ≤ Real.arctan (99 / 200 / ζ) := arctan_div_ge_of_nonneg (by norm_num) hζ h2.le (by norm_num)
    have : Real.arctan (219 / 200 / ζ) ≤ Real.arctan (219 / 4 : ℝ) := arctan_div_le_of_nonneg (by norm_num) (by norm_num) h1.le (by norm_num)
    have : Real.arctan (9 / 10 : ℝ) ≤ Real.arctan (9 / 200 / ζ) := arctan_div_ge_of_nonneg (by norm_num) hζ h2.le (by norm_num)
    have : Real.arctan (28 / 25 / ζ) ≤ Real.arctan (56 : ℝ) := arctan_div_le_of_nonneg (by norm_num) (by norm_num) h1.le (by norm_num)
    have : Real.arctan (2 / 5 : ℝ) ≤ Real.arctan (1 / 50 / ζ) := arctan_div_ge_of_nonneg (by norm_num) hζ h2.le (by norm_num)
    have : Real.arctan (229 / 200 / ζ) ≤ Real.arctan (229 / 4 : ℝ) := arctan_div_le_of_nonneg (by norm_num) (by norm_num) h1.le (by norm_num)
    have : -Real.arctan (1 / 4 : ℝ) ≤ Real.arctan (-(1 / 200) / ζ) := arctan_div_ge_of_nonpos' (by norm_num) (by norm_num) h1.le (by norm_num)
    have : Real.arctan (239 / 200 / ζ) ≤ Real.arctan (239 / 4 : ℝ) := arctan_div_le_of_nonneg (by norm_num) (by norm_num) h1.le (by norm_num)
    have : -Real.arctan (11 / 4 : ℝ) ≤ Real.arctan (-(11 / 200) / ζ) := arctan_div_ge_of_nonpos' (by norm_num) (by norm_num) h1.le (by norm_num)
    have : Real.arctan (61 / 50 / ζ) ≤ Real.arctan (61 : ℝ) := arctan_div_le_of_nonneg (by norm_num) (by norm_num) h1.le (by norm_num)
    have : -Real.arctan (4 : ℝ) ≤ Real.arctan (-(2 / 25) / ζ) := arctan_div_ge_of_nonpos' (by norm_num) (by norm_num) h1.le (by norm_num)
    have : Real.arctan (107 / 5 : ℝ) ≤ Real.arctan (107 / 100 / ζ) := arctan_div_ge_of_nonneg (by norm_num) hζ h2.le (by norm_num)
    have : Real.arctan (7 / 100 / ζ) ≤ Real.arctan (7 / 2 : ℝ) := arctan_div_le_of_nonneg (by norm_num) (by norm_num) h1.le (by norm_num)
    unfold dPsi
    linarith [va5, va15, va6, va16, va7, va17, va8, va9, va10, va11, va12, va13, va18, va14, Real.pi_gt_d20, Real.pi_lt_d20]
  intro η h1 h2
  have h := Psi_le_of_deriv (l := (1 / 50 : ℝ)) (r := (1 / 20 : ℝ)) (M := (184363 / 100000 : ℝ)) (by norm_num) hM (by norm_num) η h1 h2
  have hB := psi_at_1
  linarith

/-- Cell `[1 / 20, 9 / 50]`: `Ψ(l) ≤ -(79329 / 100000)`, `Ψ' ≤ 493239 / 1000000`, bound `-0.729169`. -/
theorem vert_cell_3 : ∀ η, (1 / 20 : ℝ) ≤ η → η ≤ (9 / 50 : ℝ) → Psi η ≤ -18 / 25 := by
  have hM : ∀ ζ, (1 / 20 : ℝ) < ζ → ζ < (9 / 50 : ℝ) → dPsi ζ ≤ (493239 / 1000000 : ℝ) := by
    intro ζ h1 h2
    have hζ : 0 < ζ := by linarith
    have : Real.arctan (129 / 200 / ζ) ≤ Real.arctan (129 / 10 : ℝ) := arctan_div_le_of_nonneg (by norm_num) (by norm_num) h1.le (by norm_num)
    have : Real.arctan (11 / 4 : ℝ) ≤ Real.arctan (99 / 200 / ζ) := arctan_div_ge_of_nonneg (by norm_num) hζ h2.le (by norm_num)
    have : Real.arctan (219 / 200 / ζ) ≤ Real.arctan (219 / 10 : ℝ) := arctan_div_le_of_nonneg (by norm_num) (by norm_num) h1.le (by norm_num)
    have : Real.arctan (1 / 4 : ℝ) ≤ Real.arctan (9 / 200 / ζ) := arctan_div_ge_of_nonneg (by norm_num) hζ h2.le (by norm_num)
    have : Real.arctan (28 / 25 / ζ) ≤ Real.arctan (112 / 5 : ℝ) := arctan_div_le_of_nonneg (by norm_num) (by norm_num) h1.le (by norm_num)
    have : Real.arctan (1 / 9 : ℝ) ≤ Real.arctan (1 / 50 / ζ) := arctan_div_ge_of_nonneg (by norm_num) hζ h2.le (by norm_num)
    have : Real.arctan (229 / 200 / ζ) ≤ Real.arctan (229 / 10 : ℝ) := arctan_div_le_of_nonneg (by norm_num) (by norm_num) h1.le (by norm_num)
    have : -Real.arctan (1 / 10 : ℝ) ≤ Real.arctan (-(1 / 200) / ζ) := arctan_div_ge_of_nonpos' (by norm_num) (by norm_num) h1.le (by norm_num)
    have : Real.arctan (239 / 200 / ζ) ≤ Real.arctan (239 / 10 : ℝ) := arctan_div_le_of_nonneg (by norm_num) (by norm_num) h1.le (by norm_num)
    have : -Real.arctan (11 / 10 : ℝ) ≤ Real.arctan (-(11 / 200) / ζ) := arctan_div_ge_of_nonpos' (by norm_num) (by norm_num) h1.le (by norm_num)
    have : Real.arctan (61 / 50 / ζ) ≤ Real.arctan (122 / 5 : ℝ) := arctan_div_le_of_nonneg (by norm_num) (by norm_num) h1.le (by norm_num)
    have : -Real.arctan (8 / 5 : ℝ) ≤ Real.arctan (-(2 / 25) / ζ) := arctan_div_ge_of_nonpos' (by norm_num) (by norm_num) h1.le (by norm_num)
    have : Real.arctan (107 / 18 : ℝ) ≤ Real.arctan (107 / 100 / ζ) := arctan_div_ge_of_nonneg (by norm_num) hζ h2.le (by norm_num)
    have : Real.arctan (7 / 100 / ζ) ≤ Real.arctan (7 / 5 : ℝ) := arctan_div_le_of_nonneg (by norm_num) (by norm_num) h1.le (by norm_num)
    unfold dPsi
    linarith [va19, va29, va20, va30, va21, va31, va22, va23, va24, va25, va26, va27, va32, va28, Real.pi_gt_d20, Real.pi_lt_d20]
  intro η h1 h2
  have h := Psi_le_of_deriv (l := (1 / 20 : ℝ)) (r := (9 / 50 : ℝ)) (M := (493239 / 1000000 : ℝ)) (by norm_num) hM (by norm_num) η h1 h2
  have hB := psi_at_2
  linarith

/-- Cell `[9 / 50, 1]`: `Ψ(l) ≤ -(157397 / 125000)`, `Ψ' ≤ 0`, bound `-1.259176`. -/
theorem vert_cell_4 : ∀ η, (9 / 50 : ℝ) ≤ η → η ≤ (1 : ℝ) → Psi η ≤ -18 / 25 := by
  have hM : ∀ ζ, (9 / 50 : ℝ) < ζ → ζ < (1 : ℝ) → dPsi ζ ≤ (0 : ℝ) := by
    intro ζ h1 h2
    have hζ : 0 < ζ := by linarith
    have : Real.arctan (129 / 200 / ζ) ≤ Real.arctan (43 / 12 : ℝ) := arctan_div_le_of_nonneg (by norm_num) (by norm_num) h1.le (by norm_num)
    have : Real.arctan (99 / 200 : ℝ) ≤ Real.arctan (99 / 200 / ζ) := arctan_div_ge_of_nonneg (by norm_num) hζ h2.le (by norm_num)
    have : Real.arctan (219 / 200 / ζ) ≤ Real.arctan (73 / 12 : ℝ) := arctan_div_le_of_nonneg (by norm_num) (by norm_num) h1.le (by norm_num)
    have : Real.arctan (9 / 200 : ℝ) ≤ Real.arctan (9 / 200 / ζ) := arctan_div_ge_of_nonneg (by norm_num) hζ h2.le (by norm_num)
    have : Real.arctan (28 / 25 / ζ) ≤ Real.arctan (56 / 9 : ℝ) := arctan_div_le_of_nonneg (by norm_num) (by norm_num) h1.le (by norm_num)
    have : Real.arctan (1 / 50 : ℝ) ≤ Real.arctan (1 / 50 / ζ) := arctan_div_ge_of_nonneg (by norm_num) hζ h2.le (by norm_num)
    have : Real.arctan (229 / 200 / ζ) ≤ Real.arctan (229 / 36 : ℝ) := arctan_div_le_of_nonneg (by norm_num) (by norm_num) h1.le (by norm_num)
    have : -Real.arctan (1 / 36 : ℝ) ≤ Real.arctan (-(1 / 200) / ζ) := arctan_div_ge_of_nonpos' (by norm_num) (by norm_num) h1.le (by norm_num)
    have : Real.arctan (239 / 200 / ζ) ≤ Real.arctan (239 / 36 : ℝ) := arctan_div_le_of_nonneg (by norm_num) (by norm_num) h1.le (by norm_num)
    have : -Real.arctan (11 / 36 : ℝ) ≤ Real.arctan (-(11 / 200) / ζ) := arctan_div_ge_of_nonpos' (by norm_num) (by norm_num) h1.le (by norm_num)
    have : Real.arctan (61 / 50 / ζ) ≤ Real.arctan (61 / 9 : ℝ) := arctan_div_le_of_nonneg (by norm_num) (by norm_num) h1.le (by norm_num)
    have : -Real.arctan (4 / 9 : ℝ) ≤ Real.arctan (-(2 / 25) / ζ) := arctan_div_ge_of_nonpos' (by norm_num) (by norm_num) h1.le (by norm_num)
    have : Real.arctan (107 / 100 : ℝ) ≤ Real.arctan (107 / 100 / ζ) := arctan_div_ge_of_nonneg (by norm_num) hζ h2.le (by norm_num)
    have : Real.arctan (7 / 100 / ζ) ≤ Real.arctan (7 / 18 : ℝ) := arctan_div_le_of_nonneg (by norm_num) (by norm_num) h1.le (by norm_num)
    unfold dPsi
    linarith [va33, va43, va34, va44, va35, va45, va36, va37, va38, va39, va40, va41, va46, va42, Real.pi_gt_d20, Real.pi_lt_d20]
  intro η h1 h2
  have h := Psi_le_of_deriv (l := (9 / 50 : ℝ)) (r := (1 : ℝ)) (M := (0 : ℝ)) (by norm_num) hM (by norm_num) η h1 h2
  have hB := psi_at_3
  linarith
/-- **(L-iii)** `Φ(7/100, η) - 2πη ≤ -18/25` for `0 < η ≤ 1`, in the form `Ψ(η) ≤ -18/25`. -/
theorem Psi_le : ∀ η ∈ Set.Ioc (0 : ℝ) 1, Psi η ≤ -18 / 25 := by
  rintro η ⟨h1, h2⟩
  rcases le_or_gt η (1 / 50 : ℝ) with c1 | c1
  · exact vert_cell_1 η (by linarith) c1
  rcases le_or_gt η (1 / 20 : ℝ) with c2 | c2
  · exact vert_cell_2 η (by linarith) c2
  rcases le_or_gt η (9 / 50 : ℝ) with c3 | c3
  · exact vert_cell_3 η (by linarith) c3
  exact vert_cell_4 η (by linarith) h2

end Zeta2.Pair.Landscape
